# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/web_page'

module Hotmeal
  module Schema
    # About Page
    #
    # Web page type: About page.
    # @see http://schema.org/AboutPage
    class AboutPage < WebPage
    end
  end
end

