# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/web_page'

module Hotmeal
  module Schema
    # About Page
    #
    # @see http://schema.org/AboutPage
    class AboutPage < WebPage
    end
  end
end
