# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/professional_service'

module Hotmeal
  module Schema
    # Accounting Service
    #
    # Accountancy business.
    # @see http://schema.org/AccountingService
    class AccountingService < ProfessionalService
    end
  end
end

