# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/action'

module Hotmeal
  module Schema
    # Achieve Action
    #
    # @see http://schema.org/AchieveAction
    #
    # Subtypes:
    # @see LoseAction
    # @see TieAction
    # @see WinAction
    class AchieveAction < Action
    end
  end
end

