# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/update_action'

module Hotmeal
  module Schema
    # Add Action
    #
    # @see http://schema.org/AddAction
    #
    # Subtypes:
    # @see InsertAction
    class AddAction < UpdateAction
    end
  end
end

