# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/entertainment_business'

module Hotmeal
  module Schema
    # Adult Entertainment
    #
    # An adult entertainment establishment.
    # @see http://schema.org/AdultEntertainment
    class AdultEntertainment < EntertainmentBusiness
    end
  end
end

