# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/offer'

module Hotmeal
  module Schema
    # Aggregate Offer
    #
    # @see http://schema.org/AggregateOffer
    class AggregateOffer < Offer
      # The highest price of all offers available.
      property :high_price, class_names: %w(Number Text), as: 'highPrice', label: 'High Price'
      # The lowest price of all offers available.
      property :low_price, class_names: %w(Number Text), as: 'lowPrice', label: 'Low Price'
      # The number of offers for the product.
      property :offer_count, class_name: 'Integer', as: 'offerCount', label: 'Offer Count'
    end
  end
end
