# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/civic_structure'

module Hotmeal
  module Schema
    # Airport
    #
    # @see http://schema.org/Airport
    class Airport < CivicStructure
    end
  end
end

