# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/civic_structure'

module Hotmeal
  module Schema
    # Airport
    #
    # An airport.
    # @see http://schema.org/Airport
    class Airport < CivicStructure
    end
  end
end

