# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/organize_action'

module Hotmeal
  module Schema
    # Allocate Action
    #
    # @see http://schema.org/AllocateAction
    #
    # Subtypes:
    # @see AcceptAction
    # @see AssignAction
    # @see AuthorizeAction
    # @see RejectAction
    class AllocateAction < OrganizeAction
      # A goal towards an action is taken. Can be concrete or abstract.
      property :purpose, class_names: %w[Thing MedicalDevicePurpose], as: 'purpose', label: 'Purpose'
    end
  end
end

