# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/entertainment_business'

module Hotmeal
  module Schema
    # Amusement Park
    #
    # @see http://schema.org/AmusementPark
    class AmusementPark < EntertainmentBusiness
    end
  end
end

