# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/local_business'

module Hotmeal
  module Schema
    # Animal Shelter
    #
    # @see http://schema.org/AnimalShelter
    class AnimalShelter < LocalBusiness
    end
  end
end
