# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/residence'

module Hotmeal
  module Schema
    # Apartment Complex
    #
    # @see http://schema.org/ApartmentComplex
    class ApartmentComplex < Residence
    end
  end
end

