# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/tech_article'

module Hotmeal
  module Schema
    # API Reference
    #
    # Reference documentation for application programming interfaces (APIs).
    # @see http://schema.org/APIReference
    class APIReference < TechArticle
      # Library file name e.g., mscorlib.dll, system.web.dll
      property :assembly, class_name: 'Text', as: 'assembly', label: 'Assembly'
      # Associated product/technology version. e.g., .NET Framework 4.5
      property :assembly_version, class_name: 'Text', as: 'assemblyVersion', label: 'Assembly Version'
      # Indicates whether API is managed or unmanaged.
      property :programming_model, class_name: 'Text', as: 'programmingModel', label: 'Programming Model'
      # Type of app development: phone, Metro style, desktop, XBox, etc.
      property :target_platform, class_name: 'Text', as: 'targetPlatform', label: 'Target Platform'
    end
  end
end

