# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/organize_action'

module Hotmeal
  module Schema
    # Apply Action
    #
    # @see http://schema.org/ApplyAction
    class ApplyAction < OrganizeAction
    end
  end
end

