# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_indication'

module Hotmeal
  module Schema
    # Approved Indication
    #
    # An indication for a medical therapy that has been formally specified or approved by a regulatory body that regulates use of the therapy; for example, the US FDA approves indications for most drugs in the US.
    # @see http://schema.org/ApprovedIndication
    class ApprovedIndication < MedicalIndication
    end
  end
end

