# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Aquarium
    #
    # Aquarium.
    # @see http://schema.org/Aquarium
    class Aquarium < CivicStructure
    end
  end
end

