# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/move_action'

module Hotmeal
  module Schema
    # Arrive Action
    #
    # @see http://schema.org/ArriveAction
    class ArriveAction < MoveAction
    end
  end
end
