# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Article
    #
    # An article, such as a news article or piece of investigative report. Newspapers and magazines have articles of many different types and this is intended to cover them all.
    # @see http://schema.org/Article
    #
    # Subtypes:
    # @see BlogPosting
    # @see NewsArticle
    # @see ScholarlyArticle
    # @see TechArticle
    class Article < CreativeWork
      # The actual body of the article.
      property :article_body, class_name: 'Text', as: 'articleBody', label: 'Article Body'
      # Articles may belong to one or more 'sections' in a magazine or newspaper, such as Sports, Lifestyle, etc.
      property :article_section, class_name: 'Text', as: 'articleSection', label: 'Article Section'
      # The number of words in the text of the Article.
      property :word_count, class_name: 'Integer', as: 'wordCount', label: 'Word Count'
    end
  end
end

