# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/communicate_action'

module Hotmeal
  module Schema
    # Ask Action
    #
    # @see http://schema.org/AskAction
    class AskAction < CommunicateAction
      # A sub property of object. A question.
      property :question, class_name: 'Text', as: 'question', label: 'Question'
    end
  end
end

