# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/action'

module Hotmeal
  module Schema
    # Assess Action
    #
    # @see http://schema.org/AssessAction
    #
    # Subtypes:
    # @see ChooseAction
    # @see IgnoreAction
    # @see ReactAction
    # @see ReviewAction
    class AssessAction < Action
    end
  end
end
