# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Attorney
    #
    # Professional service: Attorney.
    # @see http://schema.org/Attorney
    class Attorney < ProfessionalService
    end
  end
end

