# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/intangible'

module Hotmeal
  module Schema
    # Audience
    #
    # @see http://schema.org/Audience
    #
    # Subtypes:
    # @see BusinessAudience
    # @see EducationalAudience
    # @see MedicalAudience
    # @see PeopleAudience
    class Audience < Intangible
      # The target group associated with a given audience (e.g. veterans, car owners, musicians, etc.)
      #       domain: Audience
      #       Range: Text
      #
      property :audience_type, class_name: 'Text', as: 'audienceType', label: 'Audience Type'
      # The geographic area associated with the audience.
      property :geographic_area, class_name: 'AdministrativeArea', as: 'geographicArea', label: 'Geographic Area'
    end
  end
end
