# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/media_object'

module Hotmeal
  module Schema
    # Audio Object
    #
    # @see http://schema.org/AudioObject
    class AudioObject < MediaObject
      # If this MediaObject is an AudioObject or VideoObject, the transcript of that object.
      property :transcript, class_name: 'Text', as: 'transcript', label: 'Transcript'
    end
  end
end

