# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/intangible'

module Hotmeal
  module Schema
    # Audience
    #
    # @see http://schema.org/Audience
    #
    # Subtypes:
    # @see EducationalAudience
    # @see MedicalAudience
    # @see PeopleAudience
    class Audience < Intangible
    end
  end
end

