# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/automotive_business'

module Hotmeal
  module Schema
    # Auto Rental
    #
    # A car rental business.
    # @see http://schema.org/AutoRental
    class AutoRental < AutomotiveBusiness
    end
  end
end

