# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Auto Dealer
    #
    # An car dealership.
    # @see http://schema.org/AutoDealer
    class AutoDealer < AutomotiveBusiness
    end
  end
end

