# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/automotive_business'

module Hotmeal
  module Schema
    # Auto Wash
    #
    # A car wash business.
    # @see http://schema.org/AutoWash
    class AutoWash < AutomotiveBusiness
    end
  end
end

