# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Auto Body Shop
    #
    # Auto body shop.
    # @see http://schema.org/AutoBodyShop
    class AutoBodyShop < AutomotiveBusiness
    end
  end
end

