# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/automotive_business'

module Hotmeal
  module Schema
    # Auto Parts Store
    #
    # @see http://schema.org/AutoPartsStore
    class AutoPartsStore < AutomotiveBusiness
    end
  end
end

