# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Automotive Business
    #
    # Car repair, sales, or parts.
    # @see http://schema.org/AutomotiveBusiness
    #
    # Subtypes:
    # @see AutoBodyShop
    # @see AutoDealer
    # @see AutoPartsStore
    # @see AutoRental
    # @see AutoRepair
    # @see AutoWash
    # @see GasStation
    # @see MotorcycleDealer
    # @see MotorcycleRepair
    class AutomotiveBusiness < LocalBusiness
    end
  end
end

