# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/financial_service'

module Hotmeal
  module Schema
    # Automated Teller
    #
    # @see http://schema.org/AutomatedTeller
    class AutomatedTeller < FinancialService
    end
  end
end
