# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/automotive_business'

module Hotmeal
  module Schema
    # Auto Body Shop
    #
    # @see http://schema.org/AutoBodyShop
    class AutoBodyShop < AutomotiveBusiness
    end
  end
end

