# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/food_establishment'

module Hotmeal
  module Schema
    # Bakery
    #
    # A bakery.
    # @see http://schema.org/Bakery
    class Bakery < FoodEstablishment
    end
  end
end

