# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Bank or Credit Union
    #
    # Bank or credit union.
    # @see http://schema.org/BankOrCreditUnion
    class BankOrCreditUnion < FinancialService
    end
  end
end

