# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Bar or Pub
    #
    # A bar or pub.
    # @see http://schema.org/BarOrPub
    class BarOrPub < FoodEstablishment
    end
  end
end

