# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/civic_structure'

module Hotmeal
  module Schema
    # Beach
    #
    # @see http://schema.org/Beach
    class Beach < CivicStructure
    end
  end
end
