# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Beauty Salon
    #
    # Beauty salon.
    # @see http://schema.org/BeautySalon
    class BeautySalon < HealthAndBeautyBusiness
    end
  end
end

