# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/health_and_beauty_business'

module Hotmeal
  module Schema
    # Beauty Salon
    #
    # @see http://schema.org/BeautySalon
    class BeautySalon < HealthAndBeautyBusiness
    end
  end
end

