# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/lodging_business'

module Hotmeal
  module Schema
    # Bed And Breakfast
    #
    # @see http://schema.org/BedAndBreakfast
    class BedAndBreakfast < LodgingBusiness
    end
  end
end

