# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Bed And Breakfast
    #
    # Bed and breakfast.
    # @see http://schema.org/BedAndBreakfast
    class BedAndBreakfast < LodgingBusiness
    end
  end
end

