# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/store'

module Hotmeal
  module Schema
    # Bike Store
    #
    # A bike store.
    # @see http://schema.org/BikeStore
    class BikeStore < Store
    end
  end
end

