# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Blog Posting
    #
    # A blog post.
    # @see http://schema.org/BlogPosting
    class BlogPosting < Article
    end
  end
end

