# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_test'

module Hotmeal
  module Schema
    # Blood Test
    #
    # @see http://schema.org/BloodTest
    class BloodTest < MedicalTest
    end
  end
end

