# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/landform'

module Hotmeal
  module Schema
    # Body of Water
    #
    # @see http://schema.org/BodyOfWater
    #
    # Subtypes:
    # @see Canal
    # @see LakeBodyOfWater
    # @see OceanBodyOfWater
    # @see Pond
    # @see Reservoir
    # @see RiverBodyOfWater
    # @see SeaBodyOfWater
    # @see Waterfall
    class BodyOfWater < Landform
    end
  end
end

