# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Bone
    #
    # Rigid connective tissue that comprises up the skeletal structure of the human body.
    # @see http://schema.org/Bone
    class Bone < AnatomicalStructure
    end
  end
end

