# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/anatomical_structure'

module Hotmeal
  module Schema
    # Bone
    #
    # @see http://schema.org/Bone
    class Bone < AnatomicalStructure
    end
  end
end

