# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Book Store
    #
    # A bookstore.
    # @see http://schema.org/BookStore
    class BookStore < Store
    end
  end
end

