# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/store'

module Hotmeal
  module Schema
    # Book Store
    #
    # @see http://schema.org/BookStore
    class BookStore < Store
    end
  end
end
