# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/enumeration'

module Hotmeal
  module Schema
    # Book Format Type
    #
    # @see http://schema.org/BookFormatType
    class BookFormatType < Enumeration
    end
  end
end

