# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/organize_action'

module Hotmeal
  module Schema
    # Bookmark Action
    #
    # @see http://schema.org/BookmarkAction
    class BookmarkAction < OrganizeAction
    end
  end
end

