# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/transfer_action'

module Hotmeal
  module Schema
    # Borrow Action
    #
    # @see http://schema.org/BorrowAction
    class BorrowAction < TransferAction
      # A sub property of participant. The person that lends the object being borrowed.
      property :lender, class_name: 'Person', as: 'lender', label: 'Lender'
    end
  end
end

