# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/sports_activity_location'

module Hotmeal
  module Schema
    # Bowling Alley
    #
    # A bowling alley.
    # @see http://schema.org/BowlingAlley
    class BowlingAlley < SportsActivityLocation
    end
  end
end

