# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Brain Structure
    #
    # Any anatomical structure which pertains to the soft nervous tissue functioning as the coordinating center of sensation and intellectual and nervous activity.
    # @see http://schema.org/BrainStructure
    class BrainStructure < AnatomicalStructure
    end
  end
end

