# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/intangible'

module Hotmeal
  module Schema
    # Brand
    #
    # @see http://schema.org/Brand
    class Brand < Intangible
      # URL of an image for the logo of the item.
      property :logo, class_names: %w[URL ImageObject], as: 'logo', label: 'Logo'
    end
  end
end

