# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Brewery
    #
    # Brewery.
    # @see http://schema.org/Brewery
    class Brewery < FoodEstablishment
    end
  end
end

