# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/publication_event'

module Hotmeal
  module Schema
    # Broadcast Event
    #
    # @see http://schema.org/BroadcastEvent
    class BroadcastEvent < PublicationEvent
    end
  end
end
