# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/place_of_worship'

module Hotmeal
  module Schema
    # Buddhist Temple
    #
    # @see http://schema.org/BuddhistTemple
    class BuddhistTemple < PlaceOfWorship
    end
  end
end

