# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Buddhist Temple
    #
    # A Buddhist temple.
    # @see http://schema.org/BuddhistTemple
    class BuddhistTemple < PlaceOfWorship
    end
  end
end

