# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Bus Station
    #
    # A bus station.
    # @see http://schema.org/BusStation
    class BusStation < CivicStructure
    end
  end
end

