# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/event'

module Hotmeal
  module Schema
    # Business Event
    #
    # @see http://schema.org/BusinessEvent
    class BusinessEvent < Event
    end
  end
end

