# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/enumeration'

module Hotmeal
  module Schema
    # Business Function
    #
    # @see http://schema.org/BusinessFunction
    class BusinessFunction < Enumeration
    end
  end
end

