# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/food_establishment'

module Hotmeal
  module Schema
    # Cafe or Coffee Shop
    #
    # @see http://schema.org/CafeOrCoffeeShop
    class CafeOrCoffeeShop < FoodEstablishment
    end
  end
end

