# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Campground
    #
    # A campground.
    # @see http://schema.org/Campground
    class Campground < CivicStructure
    end
  end
end

