# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/body_of_water'

module Hotmeal
  module Schema
    # Canal
    #
    # @see http://schema.org/Canal
    class Canal < BodyOfWater
    end
  end
end

