# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Casino
    #
    # A casino.
    # @see http://schema.org/Casino
    class Casino < EntertainmentBusiness
    end
  end
end

