# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/entertainment_business'

module Hotmeal
  module Schema
    # Casino
    #
    # @see http://schema.org/Casino
    class Casino < EntertainmentBusiness
    end
  end
end

