# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/place_of_worship'

module Hotmeal
  module Schema
    # Catholic Church
    #
    # @see http://schema.org/CatholicChurch
    class CatholicChurch < PlaceOfWorship
    end
  end
end

