# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Catholic Church
    #
    # A Catholic church.
    # @see http://schema.org/CatholicChurch
    class CatholicChurch < PlaceOfWorship
    end
  end
end

