# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/civic_structure'

module Hotmeal
  module Schema
    # Cemetery
    #
    # @see http://schema.org/Cemetery
    class Cemetery < CivicStructure
    end
  end
end
