# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/communicate_action'

module Hotmeal
  module Schema
    # Check in Action
    #
    # @see http://schema.org/CheckInAction
    class CheckInAction < CommunicateAction
    end
  end
end

