# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/find_action'

module Hotmeal
  module Schema
    # Check Action
    #
    # @see http://schema.org/CheckAction
    class CheckAction < FindAction
    end
  end
end

