# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/web_page'

module Hotmeal
  module Schema
    # Checkout Page
    #
    # @see http://schema.org/CheckoutPage
    class CheckoutPage < WebPage
    end
  end
end
