# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Checkout Page
    #
    # Web page type: Checkout page.
    # @see http://schema.org/CheckoutPage
    class CheckoutPage < WebPage
    end
  end
end

