# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Childrens Event
    #
    # Event type: Children's event.
    # @see http://schema.org/ChildrensEvent
    class ChildrensEvent < Event
    end
  end
end

