# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Child Care
    #
    # A Childcare center.
    # @see http://schema.org/ChildCare
    class ChildCare < LocalBusiness
    end
  end
end

