# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/local_business'

module Hotmeal
  module Schema
    # Child Care
    #
    # @see http://schema.org/ChildCare
    class ChildCare < LocalBusiness
    end
  end
end

