# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/assess_action'

module Hotmeal
  module Schema
    # Choose Action
    #
    # @see http://schema.org/ChooseAction
    #
    # Subtypes:
    # @see VoteAction
    class ChooseAction < AssessAction
      # A sub property of object. The options subject to this action.
      property :option, class_names: %w(Text Thing), as: 'option', label: 'Option'
    end
  end
end
