# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Church
    #
    # A church.
    # @see http://schema.org/Church
    class Church < PlaceOfWorship
    end
  end
end

