# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/place_of_worship'

module Hotmeal
  module Schema
    # Church
    #
    # @see http://schema.org/Church
    class Church < PlaceOfWorship
    end
  end
end

