# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # City
    #
    # A city or town.
    # @see http://schema.org/City
    class City < AdministrativeArea
    end
  end
end

