# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/government_building'

module Hotmeal
  module Schema
    # City Hall
    #
    # @see http://schema.org/CityHall
    class CityHall < GovernmentBuilding
    end
  end
end
