# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/administrative_area'

module Hotmeal
  module Schema
    # City
    #
    # @see http://schema.org/City
    class City < AdministrativeArea
    end
  end
end
