# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Class
    #
    # A class, also often called a 'Type'; equivalent to rdfs:Class.
    # @see http://schema.org/Class
    class Class < Thing
    end
  end
end

