# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/thing'

module Hotmeal
  module Schema
    # Class
    #
    # @see http://schema.org/Class
    class Class < Thing
    end
  end
end
