# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/store'

module Hotmeal
  module Schema
    # Clothing Store
    #
    # @see http://schema.org/ClothingStore
    class ClothingStore < Store
    end
  end
end

