# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Clothing Store
    #
    # A clothing store.
    # @see http://schema.org/ClothingStore
    class ClothingStore < Store
    end
  end
end

