# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/creative_work'

module Hotmeal
  module Schema
    # Code
    #
    # @see http://schema.org/Code
    class Code < CreativeWork
      # Link to the repository where the un-compiled, human readable code and related code is located (SVN, github, CodePlex)
      property :code_repository, class_name: 'URL', as: 'codeRepository', label: 'Code Repository'
      # The computer programming language.
      property :programming_language, class_name: 'Thing', as: 'programmingLanguage', label: 'Programming Language'
      # Runtime platform or script interpreter dependencies (Example - Java v1, Python2.3, .Net Framework 3.0)
      property :runtime, class_name: 'Text', as: 'runtime', label: 'Runtime'
      # Full (compile ready) solution, code snippet, inline code, scripts, template.
      property :sample_type, class_name: 'Text', as: 'sampleType', label: 'Sample Type'
      # Target Operating System / Product to which the code applies.  If applies to several versions, just the product name can be used.
      property :target_product, class_name: 'SoftwareApplication', as: 'targetProduct', label: 'Target Product'
    end
  end
end

