# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/educational_organization'

module Hotmeal
  module Schema
    # College or University
    #
    # @see http://schema.org/CollegeOrUniversity
    class CollegeOrUniversity < EducationalOrganization
    end
  end
end

