# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Collection Page
    #
    # Web page type: Collection page.
    # @see http://schema.org/CollectionPage
    #
    # Subtypes:
    # @see ImageGallery
    # @see VideoGallery
    class CollectionPage < WebPage
    end
  end
end

