# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/web_page'

module Hotmeal
  module Schema
    # Collection Page
    #
    # @see http://schema.org/CollectionPage
    #
    # Subtypes:
    # @see ImageGallery
    # @see VideoGallery
    class CollectionPage < WebPage
    end
  end
end

