# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Comedy Event
    #
    # Event type: Comedy event.
    # @see http://schema.org/ComedyEvent
    class ComedyEvent < Event
    end
  end
end

