# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/entertainment_business'

module Hotmeal
  module Schema
    # Comedy Club
    #
    # @see http://schema.org/ComedyClub
    class ComedyClub < EntertainmentBusiness
    end
  end
end

