# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/creative_work'

module Hotmeal
  module Schema
    # Comment
    #
    # @see http://schema.org/Comment
    class Comment < CreativeWork
    end
  end
end
