# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/communicate_action'

module Hotmeal
  module Schema
    # Comment Action
    #
    # @see http://schema.org/CommentAction
    class CommentAction < CommunicateAction
    end
  end
end

