# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/store'

module Hotmeal
  module Schema
    # Computer Store
    #
    # @see http://schema.org/ComputerStore
    class ComputerStore < Store
    end
  end
end

