# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/action'

module Hotmeal
  module Schema
    # Consume Action
    #
    # @see http://schema.org/ConsumeAction
    #
    # Subtypes:
    # @see DrinkAction
    # @see EatAction
    # @see InstallAction
    # @see ListenAction
    # @see ReadAction
    # @see UseAction
    # @see ViewAction
    # @see WatchAction
    class ConsumeAction < Action
    end
  end
end

