# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/landform'

module Hotmeal
  module Schema
    # Continent
    #
    # @see http://schema.org/Continent
    class Continent < Landform
    end
  end
end
