# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Contact Page
    #
    # Web page type: Contact page.
    # @see http://schema.org/ContactPage
    class ContactPage < WebPage
    end
  end
end

