# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/administrative_area'

module Hotmeal
  module Schema
    # Country
    #
    # A country.
    # @see http://schema.org/Country
    class Country < AdministrativeArea
    end
  end
end

