# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/thing'

module Hotmeal
  module Schema
    # Creative Work
    #
    # @see http://schema.org/CreativeWork
    #
    # Subtypes:
    # @see Article
    # @see Blog
    # @see Book
    # @see Clip
    # @see Code
    # @see Comment
    # @see DataCatalog
    # @see Dataset
    # @see Diet
    # @see Episode
    # @see ExercisePlan
    # @see ItemList
    # @see Map
    # @see MediaObject
    # @see Movie
    # @see MusicPlaylist
    # @see MusicRecording
    # @see Painting
    # @see Photograph
    # @see Recipe
    # @see Review
    # @see Sculpture
    # @see Season
    # @see Series
    # @see SoftwareApplication
    # @see TVSeason
    # @see TVSeries
    # @see WebPage
    # @see WebPageElement
    class CreativeWork < Thing
      # The subject matter of the content.
      property :about, class_name: 'Thing', as: 'about', label: 'About'
      # Indicates that the resource is compatible with the referenced accessibility API (WebSchemas wiki lists possible values).
      #
      property :accessibility_api, class_name: 'Text', as: 'accessibilityAPI', label: 'Accessibility API'
      # Identifies input methods that are sufficient to fully control the described resource (WebSchemas wiki lists possible values).
      property :accessibility_control, class_name: 'Text', as: 'accessibilityControl', label: 'Accessibility Control'
      # Content features of the resource, such as accessible media, alternatives and supported enhancements for accessibility (WebSchemas wiki lists possible values).
      property :accessibility_feature, class_name: 'Text', as: 'accessibilityFeature', label: 'Accessibility Feature'
      # A characteristic of the described resource that is physiologically dangerous to some users. Related to WCAG 2.0 guideline 2.3. (WebSchemas wiki lists possible values)
      property :accessibility_hazard, class_name: 'Text', as: 'accessibilityHazard', label: 'Accessibility Hazard'
      # Specifies the Person that is legally accountable for the CreativeWork.
      property :accountable_person, class_name: 'Person', as: 'accountablePerson', label: 'Accountable Person'
      # The overall rating, based on a collection of reviews or ratings, of the item.
      property :aggregate_rating, class_name: 'AggregateRating', as: 'aggregateRating', label: 'Aggregate Rating'
      # A secondary title of the CreativeWork.
      property :alternative_headline, class_name: 'Text', as: 'alternativeHeadline', label: 'Alternative Headline'
      # The media objects that encode this creative work. This property is a synonym for encodings.
      property :associated_media, class_name: 'MediaObject', as: 'associatedMedia', label: 'Associated Media'
      # The intended audience of the item, i.e. the group for whom the item was created.
      property :audience, class_name: 'Audience', as: 'audience', label: 'Audience'
      # An embedded audio object.
      property :audio, class_name: 'AudioObject', as: 'audio', label: 'Audio'
      # The author of this content. Please note that author is special in that HTML 5 provides a special mechanism for indicating authorship via the rel tag. That is equivalent to this and may be used interchangeably.
      property :author, class_names: %w(Organization Person), as: 'author', label: 'Author'
      # An award won by this person or for this creative work.
      property :award, class_name: 'Text', as: 'award', label: 'Award'
      # Awards won by this person or for this creative work. (legacy spelling; see singular form, award)
      property :awards, class_name: 'Text', as: 'awards', label: 'Awards'
      # A citation or reference to another creative work, such as another publication, web page, scholarly article, etc.
      property :citation, class_names: %w(CreativeWork Text), as: 'citation', label: 'Citation'
      # Comments, typically from users, on this CreativeWork.
      property :comment, class_name: 'UserComments', as: 'comment', label: 'Comment'
      # The location of the content.
      property :content_location, class_name: 'Place', as: 'contentLocation', label: 'Content Location'
      # Official rating of a piece of content—for example,'MPAA PG-13'.
      property :content_rating, class_name: 'Text', as: 'contentRating', label: 'Content Rating'
      # A secondary contributor to the CreativeWork.
      property :contributor, class_names: %w(Organization Person), as: 'contributor', label: 'Contributor'
      # The party holding the legal copyright to the CreativeWork.
      property :copyright_holder, class_names: %w(Organization Person), as: 'copyrightHolder', label: 'Copyright Holder'
      # The year during which the claimed copyright for the CreativeWork was first asserted.
      property :copyright_year, class_name: 'Number', as: 'copyrightYear', label: 'Copyright Year'
      # The creator/author of this CreativeWork or UserComments. This is the same as the Author property for CreativeWork.
      property :creator, class_names: %w(Organization Person), as: 'creator', label: 'Creator'
      # The date on which the CreativeWork was created.
      property :date_created, class_name: 'Date', as: 'dateCreated', label: 'Date Created'
      # The date on which the CreativeWork was most recently modified.
      property :date_modified, class_name: 'Date', as: 'dateModified', label: 'Date Modified'
      # Date of first broadcast/publication.
      property :date_published, class_name: 'Date', as: 'datePublished', label: 'Date Published'
      # A link to the page containing the comments of the CreativeWork.
      property :discussion_url, class_name: 'URL', as: 'discussionUrl', label: 'Discussion Url'
      # Specifies the Person who edited the CreativeWork.
      property :editor, class_name: 'Person', as: 'editor', label: 'Editor'
      # An alignment to an established educational framework.
      property :educational_alignment, class_name: 'AlignmentObject', as: 'educationalAlignment', label: 'Educational Alignment'
      # The purpose of a work in the context of education; for example, 'assignment', 'group work'.
      property :educational_use, class_name: 'Text', as: 'educationalUse', label: 'Educational Use'
      # A media object that encode this CreativeWork.
      property :encoding, class_name: 'MediaObject', as: 'encoding', label: 'Encoding'
      # The media objects that encode this creative work (legacy spelling; see singular form, encoding).
      property :encodings, class_name: 'MediaObject', as: 'encodings', label: 'Encodings'
      # Genre of the creative work
      property :genre, class_name: 'Text', as: 'genre', label: 'Genre'
      # Headline of the article
      property :headline, class_name: 'Text', as: 'headline', label: 'Headline'
      # The language of the content. please use one of the language codes from the IETF BCP 47 standard.
      property :in_language, class_name: 'Text', as: 'inLanguage', label: 'In Language'
      # A count of a specific user interactions with this item—for example, 20 UserLikes, 5 UserComments, or 300 UserDownloads. The user interaction type should be one of the sub types of UserInteraction.
      property :interaction_count, class_name: 'Text', as: 'interactionCount', label: 'Interaction Count'
      # The predominant mode of learning supported by the learning resource. Acceptable values are 'active', 'expositive', or 'mixed'.
      property :interactivity_type, class_name: 'Text', as: 'interactivityType', label: 'Interactivity Type'
      # A resource that was used in the creation of this resource. This term can be repeated for multiple sources. For example, http://example.com/great-multiplication-intro.html
      property :is_based_on_url, class_name: 'URL', as: 'isBasedOnUrl', label: 'Is Based On Url'
      # Indicates whether this content is family friendly.
      property :is_family_friendly, class_name: 'Boolean', as: 'isFamilyFriendly', label: 'Is Family Friendly'
      # The keywords/tags used to describe this content.
      property :keywords, class_name: 'Text', as: 'keywords', label: 'Keywords'
      # The predominant type or kind characterizing the learning resource. For example, 'presentation', 'handout'.
      property :learning_resource_type, class_name: 'Text', as: 'learningResourceType', label: 'Learning Resource Type'
      # Indicates that the CreativeWork contains a reference to, but is not necessarily about a concept.
      property :mentions, class_name: 'Thing', as: 'mentions', label: 'Mentions'
      # An offer to transfer some rights to an item or to provide a service—for example, an offer to sell tickets to an event, to rent the DVD of a movie, to stream a TV show over the internet, to repair a motorcycle, or to loan a book.
      property :offers, class_name: 'Offer', as: 'offers', label: 'Offers'
      # The organization or agency that is providing the service.
      property :provider, class_names: %w(Organization Person), as: 'provider', label: 'Provider'
      # The publisher of the creative work.
      property :publisher, class_name: 'Organization', as: 'publisher', label: 'Publisher'
      # Link to page describing the editorial principles of the organization primarily responsible for the creation of the CreativeWork.
      property :publishing_principles, class_name: 'URL', as: 'publishingPrinciples', label: 'Publishing Principles'
      # A review of the item.
      property :review, class_name: 'Review', as: 'review', label: 'Review'
      # Review of the item (legacy spelling; see singular form, review).
      property :reviews, class_name: 'Review', as: 'reviews', label: 'Reviews'
      # The Organization on whose behalf the creator was working.
      property :source_organization, class_name: 'Organization', as: 'sourceOrganization', label: 'Source Organization'
      # The textual content of this CreativeWork.
      property :text, class_name: 'Text', as: 'text', label: 'Text'
      # A thumbnail image relevant to the Thing.
      property :thumbnail_url, class_name: 'URL', as: 'thumbnailUrl', label: 'Thumbnail Url'
      # Approximate or typical time it takes to work with or through this learning resource for the typical intended target audience, e.g. 'P30M', 'P1H25M'.
      property :time_required, class_name: 'Duration', as: 'timeRequired', label: 'Time Required'
      # The typical expected age range, e.g. '7-9', '11-'.
      property :typical_age_range, class_name: 'Text', as: 'typicalAgeRange', label: 'Typical Age Range'
      # The version of the CreativeWork embodied by a specified resource.
      property :version, class_name: 'Number', as: 'version', label: 'Version'
      # An embedded video object.
      property :video, class_name: 'VideoObject', as: 'video', label: 'Video'
    end
  end
end
