# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/payment_method'

module Hotmeal
  module Schema
    # Credit Card
    #
    # @see http://schema.org/CreditCard
    class CreditCard < PaymentMethod
    end
  end
end

