# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Crematorium
    #
    # A crematorium.
    # @see http://schema.org/Crematorium
    class Crematorium < CivicStructure
    end
  end
end

