# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/event'

module Hotmeal
  module Schema
    # Dance Event
    #
    # Event type: A social dance.
    # @see http://schema.org/DanceEvent
    class DanceEvent < Event
    end
  end
end

