# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/creative_work'

module Hotmeal
  module Schema
    # Data Catalog
    #
    # @see http://schema.org/DataCatalog
    class DataCatalog < CreativeWork
      # A dataset contained in a catalog.
      property :dataset, class_name: 'Dataset', as: 'dataset', label: 'Dataset'
    end
  end
end
