# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Data Catalog
    #
    # A collection of datasets.
    # @see http://schema.org/DataCatalog
    class DataCatalog < CreativeWork
      # A dataset contained in a catalog.
      property :dataset, class_name: 'Dataset', as: 'dataset', label: 'Dataset'
    end
  end
end

