# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/media_object'

module Hotmeal
  module Schema
    # Data Download
    #
    # @see http://schema.org/DataDownload
    class DataDownload < MediaObject
    end
  end
end

