# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Data Download
    #
    # A dataset in downloadable form.
    # @see http://schema.org/DataDownload
    class DataDownload < MediaObject
    end
  end
end

