# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/enumeration'

module Hotmeal
  module Schema
    # Day of Week
    #
    # @see http://schema.org/DayOfWeek
    class DayOfWeek < Enumeration
    end
  end
end

