# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/health_and_beauty_business'

module Hotmeal
  module Schema
    # Day Spa
    #
    # A day spa.
    # @see http://schema.org/DaySpa
    class DaySpa < HealthAndBeautyBusiness
    end
  end
end

