# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/government_building'

module Hotmeal
  module Schema
    # Defence Establishment
    #
    # A defence establishment, such as an army or navy base.
    # @see http://schema.org/DefenceEstablishment
    class DefenceEstablishment < GovernmentBuilding
    end
  end
end

