# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/update_action'

module Hotmeal
  module Schema
    # Delete Action
    #
    # @see http://schema.org/DeleteAction
    class DeleteAction < UpdateAction
    end
  end
end

