# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/enumeration'

module Hotmeal
  module Schema
    # Delivery Method
    #
    # @see http://schema.org/DeliveryMethod
    #
    # Subtypes:
    # @see LockerDelivery
    # @see OnSitePickup
    # @see ParcelService
    class DeliveryMethod < Enumeration
    end
  end
end

