# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_organization'

module Hotmeal
  module Schema
    # Dentist
    #
    # @see http://schema.org/Dentist
    class Dentist < MedicalOrganization
    end
  end
end

