# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Dentist
    #
    # A dentist.
    # @see http://schema.org/Dentist
    class Dentist < MedicalOrganization
    end
  end
end

