# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/store'

module Hotmeal
  module Schema
    # Department Store
    #
    # A department store.
    # @see http://schema.org/DepartmentStore
    class DepartmentStore < Store
    end
  end
end

