# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/move_action'

module Hotmeal
  module Schema
    # Depart Action
    #
    # @see http://schema.org/DepartAction
    class DepartAction < MoveAction
    end
  end
end

