# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_procedure'

module Hotmeal
  module Schema
    # Diagnostic Procedure
    #
    # @see http://schema.org/DiagnosticProcedure
    class DiagnosticProcedure < MedicalProcedure
    end
  end
end

