# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_organization'

module Hotmeal
  module Schema
    # Diagnostic Lab
    #
    # A medical laboratory that offers on-site or off-site diagnostic services.
    # @see http://schema.org/DiagnosticLab
    class DiagnosticLab < MedicalOrganization
      # A diagnostic test or procedure offered by this lab.
      property :available_test, class_name: 'MedicalTest', as: 'availableTest', label: 'Available Test'
    end
  end
end

