# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/react_action'

module Hotmeal
  module Schema
    # Disagree Action
    #
    # @see http://schema.org/DisagreeAction
    class DisagreeAction < ReactAction
    end
  end
end
