# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Distance
    #
    # Properties that take Distances as values are of the form '<Number> <Length unit of measure>'. E.g., '7 ft'
    # @see http://schema.org/Distance
    class Distance < Quantity
    end
  end
end

