# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/quantity'

module Hotmeal
  module Schema
    # Distance
    #
    # @see http://schema.org/Distance
    class Distance < Quantity
    end
  end
end
