# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/transfer_action'

module Hotmeal
  module Schema
    # Download Action
    #
    # @see http://schema.org/DownloadAction
    class DownloadAction < TransferAction
    end
  end
end

