# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/create_action'

module Hotmeal
  module Schema
    # Draw Action
    #
    # @see http://schema.org/DrawAction
    class DrawAction < CreateAction
    end
  end
end

