# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Drug Legal Status
    #
    # The legal availability status of a medical drug.
    # @see http://schema.org/DrugLegalStatus
    class DrugLegalStatus < MedicalIntangible
      # The location in which the status applies.
      property :applicable_location, class_name: 'AdministrativeArea', as: 'applicableLocation', label: 'Applicable Location'
    end
  end
end

