# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_enumeration'

module Hotmeal
  module Schema
    # Drug Prescription Status
    #
    # Indicates whether this drug is available by prescription or over-the-counter.
    # @see http://schema.org/DrugPrescriptionStatus
    class DrugPrescriptionStatus < MedicalEnumeration
    end
  end
end

