# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_therapy'

module Hotmeal
  module Schema
    # Drug Class
    #
    # @see http://schema.org/DrugClass
    class DrugClass < MedicalTherapy
      # A drug in this drug class.
      property :drug, class_name: 'Drug', as: 'drug', label: 'Drug'
    end
  end
end

