# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_enumeration'

module Hotmeal
  module Schema
    # Drug Cost Category
    #
    # @see http://schema.org/DrugCostCategory
    class DrugCostCategory < MedicalEnumeration
    end
  end
end

