# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Drug Cost Category
    #
    # Enumerated categories of medical drug costs.
    # @see http://schema.org/DrugCostCategory
    class DrugCostCategory < MedicalEnumeration
    end
  end
end

