# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_enumeration'

module Hotmeal
  module Schema
    # Drug Prescription Status
    #
    # @see http://schema.org/DrugPrescriptionStatus
    class DrugPrescriptionStatus < MedicalEnumeration
    end
  end
end

