# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_enumeration'

module Hotmeal
  module Schema
    # Drug Pregnancy Category
    #
    # Categories that represent an assessment of the risk of fetal injury due to a drug or pharmaceutical used as directed by the mother during pregnancy.
    # @see http://schema.org/DrugPregnancyCategory
    class DrugPregnancyCategory < MedicalEnumeration
    end
  end
end

