# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Dry Cleaning or Laundry
    #
    # A dry-cleaning business.
    # @see http://schema.org/DryCleaningOrLaundry
    class DryCleaningOrLaundry < LocalBusiness
    end
  end
end

