# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/quantity'

module Hotmeal
  module Schema
    # Duration
    #
    # @see http://schema.org/Duration
    class Duration < Quantity
    end
  end
end
