# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/organization'

module Hotmeal
  module Schema
    # Educational Organization
    #
    # @see http://schema.org/EducationalOrganization
    #
    # Subtypes:
    # @see CollegeOrUniversity
    # @see ElementarySchool
    # @see HighSchool
    # @see MiddleSchool
    # @see Preschool
    # @see School
    class EducationalOrganization < Organization
      # Alumni of educational organization.
      property :alumni, class_name: 'Person', as: 'alumni', label: 'Alumni'
    end
  end
end

