# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Electronics Store
    #
    # An electronics store.
    # @see http://schema.org/ElectronicsStore
    class ElectronicsStore < Store
    end
  end
end

