# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Electrician
    #
    # An electrician.
    # @see http://schema.org/Electrician
    class Electrician < ProfessionalService
    end
  end
end

