# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/store'

module Hotmeal
  module Schema
    # Electronics Store
    #
    # @see http://schema.org/ElectronicsStore
    class ElectronicsStore < Store
    end
  end
end

