# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/educational_organization'

module Hotmeal
  module Schema
    # Elementary School
    #
    # @see http://schema.org/ElementarySchool
    class ElementarySchool < EducationalOrganization
    end
  end
end
