# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Embassy
    #
    # An embassy.
    # @see http://schema.org/Embassy
    class Embassy < GovernmentBuilding
    end
  end
end

