# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/local_business'

module Hotmeal
  module Schema
    # Emergency Service
    #
    # @see http://schema.org/EmergencyService
    #
    # Subtypes:
    # @see FireStation
    # @see Hospital
    # @see PoliceStation
    class EmergencyService < LocalBusiness
    end
  end
end

