# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Employment Agency
    #
    # An employment agency.
    # @see http://schema.org/EmploymentAgency
    class EmploymentAgency < LocalBusiness
    end
  end
end

