# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/react_action'

module Hotmeal
  module Schema
    # Endorse Action
    #
    # @see http://schema.org/EndorseAction
    class EndorseAction < ReactAction
      # A sub property of participant. The person/organization being supported.
      property :endorsee, class_names: %w(Organization Person), as: 'endorsee', label: 'Endorsee'
    end
  end
end
