# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/quantity'

module Hotmeal
  module Schema
    # Energy
    #
    # Properties that take Enerygy as values are of the form '<Number> <Energy unit of measure>'
    # @see http://schema.org/Energy
    class Energy < Quantity
    end
  end
end

