# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/quantity'

module Hotmeal
  module Schema
    # Energy
    #
    # @see http://schema.org/Energy
    class Energy < Quantity
    end
  end
end

