# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/local_business'

module Hotmeal
  module Schema
    # Entertainment Business
    #
    # @see http://schema.org/EntertainmentBusiness
    #
    # Subtypes:
    # @see AdultEntertainment
    # @see AmusementPark
    # @see ArtGallery
    # @see Casino
    # @see ComedyClub
    # @see MovieTheater
    # @see NightClub
    class EntertainmentBusiness < LocalBusiness
    end
  end
end

