# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Entertainment Business
    #
    # A business providing entertainment.
    # @see http://schema.org/EntertainmentBusiness
    #
    # Subtypes:
    # @see AdultEntertainment
    # @see AmusementPark
    # @see ArtGallery
    # @see Casino
    # @see ComedyClub
    # @see MovieTheater
    # @see NightClub
    class EntertainmentBusiness < LocalBusiness
    end
  end
end

