# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/intangible'

module Hotmeal
  module Schema
    # Enumeration
    #
    # Lists or enumerations—for example, a list of cuisines or music genres, etc.
    # @see http://schema.org/Enumeration
    #
    # Subtypes:
    # @see BookFormatType
    # @see BusinessEntityType
    # @see BusinessFunction
    # @see DayOfWeek
    # @see DeliveryMethod
    # @see ItemAvailability
    # @see OfferItemCondition
    # @see PaymentMethod
    # @see QualitativeValue
    # @see Specialty
    # @see WarrantyScope
    class Enumeration < Intangible
    end
  end
end

