# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/thing'

module Hotmeal
  module Schema
    # Event
    #
    # @see http://schema.org/Event
    #
    # Subtypes:
    # @see BusinessEvent
    # @see ChildrensEvent
    # @see ComedyEvent
    # @see DanceEvent
    # @see EducationEvent
    # @see Festival
    # @see FoodEvent
    # @see LiteraryEvent
    # @see MusicEvent
    # @see SaleEvent
    # @see SocialEvent
    # @see SportsEvent
    # @see TheaterEvent
    # @see UserInteraction
    # @see VisualArtsEvent
    class Event < Thing
      # A person or organization attending the event.
      property :attendee, class_names: %w[Organization Person], as: 'attendee', label: 'Attendee'
      # A person attending the event (legacy spelling; see singular form, attendee).
      property :attendees, class_names: %w[Organization Person], as: 'attendees', label: 'Attendees'
      # The duration of the item (movie, audio recording, event, etc.) in ISO 8601 date format.
      property :duration, class_name: 'Duration', as: 'duration', label: 'Duration'
      # The end date and time of the event (in ISO 8601 date format).
      property :end_date, class_name: 'Date', as: 'endDate', label: 'End Date'
      # The location of the event, organization or action.
      property :location, class_names: %w[PostalAddress Place], as: 'location', label: 'Location'
      # An offer to sell this item—for example, an offer to sell a product, the DVD of a movie, or tickets to an event.
      property :offers, class_name: 'Offer', as: 'offers', label: 'Offers'
      # A performer at the event—for example, a presenter, musician, musical group or actor.
      property :performer, class_names: %w[Organization Person], as: 'performer', label: 'Performer'
      # The main performer or performers of the event—for example, a presenter, musician, or actor (legacy spelling; see singular form, performer).
      property :performers, class_names: %w[Organization Person], as: 'performers', label: 'Performers'
      # The start date and time of the event (in ISO 8601 date format).
      property :start_date, class_name: 'Date', as: 'startDate', label: 'Start Date'
      # An Event that is part of this event. For example, a conference event includes many presentations, each are a subEvent of the conference.
      property :sub_event, class_name: 'Event', as: 'subEvent', label: 'Sub Event'
      # Events that are a part of this event. For example, a conference event includes many presentations, each are subEvents of the conference (legacy spelling; see singular form, subEvent).
      property :sub_events, class_name: 'Event', as: 'subEvents', label: 'Sub Events'
      # An event that this event is a part of. For example, a collection of individual music performances might each have a music festival as their superEvent.
      property :super_event, class_name: 'Event', as: 'superEvent', label: 'Super Event'
    end
  end
end

