# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/enumeration'

module Hotmeal
  module Schema
    # Event Status Type
    #
    # @see http://schema.org/EventStatusType
    class EventStatusType < Enumeration
    end
  end
end

