# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/civic_structure'

module Hotmeal
  module Schema
    # Event Venue
    #
    # An event venue.
    # @see http://schema.org/EventVenue
    class EventVenue < CivicStructure
    end
  end
end

