# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Exercise Gym
    #
    # A gym.
    # @see http://schema.org/ExerciseGym
    class ExerciseGym < SportsActivityLocation
    end
  end
end

