# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Fast Food Restaurant
    #
    # A fast-food restaurant.
    # @see http://schema.org/FastFoodRestaurant
    class FastFoodRestaurant < FoodEstablishment
    end
  end
end

