# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/food_establishment'

module Hotmeal
  module Schema
    # Fast Food Restaurant
    #
    # @see http://schema.org/FastFoodRestaurant
    class FastFoodRestaurant < FoodEstablishment
    end
  end
end

