# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/event'

module Hotmeal
  module Schema
    # Festival
    #
    # @see http://schema.org/Festival
    class Festival < Event
    end
  end
end

