# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Festival
    #
    # Event type: Festival.
    # @see http://schema.org/Festival
    class Festival < Event
    end
  end
end

