# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/local_business'

module Hotmeal
  module Schema
    # Financial Service
    #
    # @see http://schema.org/FinancialService
    #
    # Subtypes:
    # @see AccountingService
    # @see AutomatedTeller
    # @see BankOrCreditUnion
    # @see InsuranceAgency
    class FinancialService < LocalBusiness
    end
  end
end

