# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Financial Service
    #
    # Financial services business.
    # @see http://schema.org/FinancialService
    #
    # Subtypes:
    # @see AccountingService
    # @see AutomatedTeller
    # @see BankOrCreditUnion
    # @see InsuranceAgency
    class FinancialService < LocalBusiness
    end
  end
end

