# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/action'

module Hotmeal
  module Schema
    # Find Action
    #
    # @see http://schema.org/FindAction
    #
    # Subtypes:
    # @see CheckAction
    # @see DiscoverAction
    # @see TrackAction
    class FindAction < Action
    end
  end
end

