# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/civic_structure'

module Hotmeal
  module Schema
    # Fire Station
    #
    # @see http://schema.org/FireStation
    class FireStation < CivicStructure
    end
  end
end

