# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/store'

module Hotmeal
  module Schema
    # Florist
    #
    # A florist.
    # @see http://schema.org/Florist
    class Florist < Store
    end
  end
end

