# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/interact_action'

module Hotmeal
  module Schema
    # Follow Action
    #
    # @see http://schema.org/FollowAction
    class FollowAction < InteractAction
      # A sub property of object. The person or organization being followed.
      property :followee, class_names: %w(Organization Person), as: 'followee', label: 'Followee'
    end
  end
end
