# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/store'

module Hotmeal
  module Schema
    # Garden Store
    #
    # A garden store.
    # @see http://schema.org/GardenStore
    class GardenStore < Store
    end
  end
end

