# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Gas Station
    #
    # A gas station.
    # @see http://schema.org/GasStation
    class GasStation < AutomotiveBusiness
    end
  end
end

