# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Gated Residence Community
    #
    # Residence type: Gated community.
    # @see http://schema.org/GatedResidenceCommunity
    class GatedResidenceCommunity < Residence
    end
  end
end

