# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/residence'

module Hotmeal
  module Schema
    # Gated Residence Community
    #
    # @see http://schema.org/GatedResidenceCommunity
    class GatedResidenceCommunity < Residence
    end
  end
end

