# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # General Contractor
    #
    # A general contractor.
    # @see http://schema.org/GeneralContractor
    class GeneralContractor < ProfessionalService
    end
  end
end

