# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/professional_service'

module Hotmeal
  module Schema
    # General Contractor
    #
    # @see http://schema.org/GeneralContractor
    class GeneralContractor < ProfessionalService
    end
  end
end

