# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/structured_value'

module Hotmeal
  module Schema
    # Geo Shape
    #
    # @see http://schema.org/GeoShape
    class GeoShape < StructuredValue
      # A polygon is the area enclosed by a point-to-point path for which the starting and ending points are the same. A polygon is expressed as a series of four or more spacedelimited points where the first and final points are identical.
      property :box, class_name: 'Text', as: 'box', label: 'Box'
      # A circle is the circular region of a specified radius centered at a specified latitude and longitude. A circle is expressed as a pair followed by a radius in meters.
      property :circle, class_name: 'Text', as: 'circle', label: 'Circle'
      # The elevation of a location.
      property :elevation, class_names: %w[Text Number], as: 'elevation', label: 'Elevation'
      # A line is a point-to-point path consisting of two or more points. A line is expressed as a series of two or more point objects separated by space.
      property :line, class_name: 'Text', as: 'line', label: 'Line'
      # A polygon is the area enclosed by a point-to-point path for which the starting and ending points are the same. A polygon is expressed as a series of four or more spacedelimited points where the first and final points are identical.
      property :polygon, class_name: 'Text', as: 'polygon', label: 'Polygon'
    end
  end
end

