# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/sports_activity_location'

module Hotmeal
  module Schema
    # Golf Course
    #
    # @see http://schema.org/GolfCourse
    class GolfCourse < SportsActivityLocation
    end
  end
end

