# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Golf Course
    #
    # A golf course.
    # @see http://schema.org/GolfCourse
    class GolfCourse < SportsActivityLocation
    end
  end
end

