# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/civic_structure'

module Hotmeal
  module Schema
    # Government Building
    #
    # @see http://schema.org/GovernmentBuilding
    #
    # Subtypes:
    # @see CityHall
    # @see Courthouse
    # @see DefenceEstablishment
    # @see Embassy
    # @see LegislativeBuilding
    class GovernmentBuilding < CivicStructure
    end
  end
end

