# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/local_business'

module Hotmeal
  module Schema
    # Government Office
    #
    # @see http://schema.org/GovernmentOffice
    #
    # Subtypes:
    # @see PostOffice
    class GovernmentOffice < LocalBusiness
    end
  end
end
