# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/permit'

module Hotmeal
  module Schema
    # Government Permit
    #
    # @see http://schema.org/GovernmentPermit
    class GovernmentPermit < Permit
    end
  end
end

