# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/service'

module Hotmeal
  module Schema
    # Government Service
    #
    # @see http://schema.org/GovernmentService
    class GovernmentService < Service
      # The operating organization, if different from the provider.  This enables the representation of services that are provided by an organization, but operated by another organization like a subcontractor.
      property :service_operator, class_name: 'Organization', as: 'serviceOperator', label: 'Service Operator'
    end
  end
end

