# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Government Organization
    #
    # A governmental organization or agency.
    # @see http://schema.org/GovernmentOrganization
    class GovernmentOrganization < Organization
    end
  end
end

