# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/organization'

module Hotmeal
  module Schema
    # Government Organization
    #
    # @see http://schema.org/GovernmentOrganization
    class GovernmentOrganization < Organization
    end
  end
end

