# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Grocery Store
    #
    # A grocery store.
    # @see http://schema.org/GroceryStore
    class GroceryStore < Store
    end
  end
end

