# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/store'

module Hotmeal
  module Schema
    # Grocery Store
    #
    # @see http://schema.org/GroceryStore
    class GroceryStore < Store
    end
  end
end

