# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/health_and_beauty_business'

module Hotmeal
  module Schema
    # Hair Salon
    #
    # @see http://schema.org/HairSalon
    class HairSalon < HealthAndBeautyBusiness
    end
  end
end
