# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/store'

module Hotmeal
  module Schema
    # Hardware Store
    #
    # A hardware store.
    # @see http://schema.org/HardwareStore
    class HardwareStore < Store
    end
  end
end

