# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Health Club
    #
    # A health club.
    # @see http://schema.org/HealthClub
    class HealthClub < HealthAndBeautyBusiness
    end
  end
end

