# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/local_business'

module Hotmeal
  module Schema
    # Health And Beauty Business
    #
    # Health and beauty.
    # @see http://schema.org/HealthAndBeautyBusiness
    #
    # Subtypes:
    # @see BeautySalon
    # @see DaySpa
    # @see HairSalon
    # @see HealthClub
    # @see NailSalon
    # @see TattooParlor
    class HealthAndBeautyBusiness < LocalBusiness
    end
  end
end

