# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # High School
    #
    # A high school.
    # @see http://schema.org/HighSchool
    class HighSchool < EducationalOrganization
    end
  end
end

