# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Hindu Temple
    #
    # A Hindu temple.
    # @see http://schema.org/HinduTemple
    class HinduTemple < PlaceOfWorship
    end
  end
end

