# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/place_of_worship'

module Hotmeal
  module Schema
    # Hindu Temple
    #
    # @see http://schema.org/HinduTemple
    class HinduTemple < PlaceOfWorship
    end
  end
end
