# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/store'

module Hotmeal
  module Schema
    # Hobby Shop
    #
    # A hobby store.
    # @see http://schema.org/HobbyShop
    class HobbyShop < Store
    end
  end
end

