# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/local_business'

module Hotmeal
  module Schema
    # Home And Construction Business
    #
    # @see http://schema.org/HomeAndConstructionBusiness
    #
    # Subtypes:
    # @see Electrician
    # @see GeneralContractor
    # @see HVACBusiness
    # @see HousePainter
    # @see Locksmith
    # @see MovingCompany
    # @see Plumber
    # @see RoofingContractor
    class HomeAndConstructionBusiness < LocalBusiness
    end
  end
end
