# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Home Goods Store
    #
    # A home goods store.
    # @see http://schema.org/HomeGoodsStore
    class HomeGoodsStore < Store
    end
  end
end

