# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Hostel
    #
    # A hostel.
    # @see http://schema.org/Hostel
    class Hostel < LodgingBusiness
    end
  end
end

