# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/lodging_business'

module Hotmeal
  module Schema
    # Hostel
    #
    # @see http://schema.org/Hostel
    class Hostel < LodgingBusiness
    end
  end
end
