# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/lodging_business'

module Hotmeal
  module Schema
    # Hotel
    #
    # A hotel.
    # @see http://schema.org/Hotel
    class Hotel < LodgingBusiness
    end
  end
end

