# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/professional_service'

module Hotmeal
  module Schema
    # House Painter
    #
    # @see http://schema.org/HousePainter
    class HousePainter < ProfessionalService
    end
  end
end

