# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/home_and_construction_business'

module Hotmeal
  module Schema
    # HVAC Business
    #
    # @see http://schema.org/HVACBusiness
    class HVACBusiness < HomeAndConstructionBusiness
    end
  end
end
