# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/food_establishment'

module Hotmeal
  module Schema
    # Ice Cream Shop
    #
    # An ice cream shop
    # @see http://schema.org/IceCreamShop
    class IceCreamShop < FoodEstablishment
    end
  end
end

