# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/assess_action'

module Hotmeal
  module Schema
    # Ignore Action
    #
    # @see http://schema.org/IgnoreAction
    class IgnoreAction < AssessAction
    end
  end
end

