# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/collection_page'

module Hotmeal
  module Schema
    # Image Gallery
    #
    # @see http://schema.org/ImageGallery
    class ImageGallery < CollectionPage
    end
  end
end

