# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Image Gallery
    #
    # Web page type: Image gallery page.
    # @see http://schema.org/ImageGallery
    class ImageGallery < CollectionPage
    end
  end
end

