# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_test'

module Hotmeal
  module Schema
    # Imaging Test
    #
    # @see http://schema.org/ImagingTest
    class ImagingTest < MedicalTest
      # Imaging technique used.
      property :imaging_technique, class_name: 'MedicalImagingTechnique', as: 'imagingTechnique', label: 'Imaging Technique'
    end
  end
end

