# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_condition'

module Hotmeal
  module Schema
    # Infectious Disease
    #
    # @see http://schema.org/InfectiousDisease
    class InfectiousDisease < MedicalCondition
      # The actual infectious agent, such as a specific bacterium.
      property :infectious_agent, class_name: 'Text', as: 'infectiousAgent', label: 'Infectious Agent'
      # The class of infectious agent (bacteria, prion, etc.) that causes the disease.
      property :infectious_agent_class, class_name: 'InfectiousAgentClass', as: 'infectiousAgentClass', label: 'Infectious Agent Class'
      # How the disease spreads, either as a route or vector, for example 'direct contact', 'Aedes aegypti', etc.
      property :transmission_method, class_name: 'Text', as: 'transmissionMethod', label: 'Transmission Method'
    end
  end
end

