# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/add_action'

module Hotmeal
  module Schema
    # Insert Action
    #
    # @see http://schema.org/InsertAction
    #
    # Subtypes:
    # @see AppendAction
    # @see PrependAction
    class InsertAction < AddAction
      # A sub property of location. The final location of the object or the agent after the action.
      property :to_location, class_names: %w[Place Number], as: 'toLocation', label: 'To Location'
    end
  end
end

