# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/consume_action'

module Hotmeal
  module Schema
    # Install Action
    #
    # @see http://schema.org/InstallAction
    class InstallAction < ConsumeAction
    end
  end
end

