# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Insurance Agency
    #
    # Insurance agency.
    # @see http://schema.org/InsuranceAgency
    class InsuranceAgency < FinancialService
    end
  end
end

