# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/financial_service'

module Hotmeal
  module Schema
    # Insurance Agency
    #
    # @see http://schema.org/InsuranceAgency
    class InsuranceAgency < FinancialService
    end
  end
end

