# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/thing'

module Hotmeal
  module Schema
    # Intangible
    #
    # A utility class that serves as the umbrella for a number of 'intangible' things such as quantities, structured values, etc.
    # @see http://schema.org/Intangible
    #
    # Subtypes:
    # @see AlignmentObject
    # @see Audience
    # @see Brand
    # @see Demand
    # @see Enumeration
    # @see JobPosting
    # @see Language
    # @see Offer
    # @see Quantity
    # @see Rating
    # @see StructuredValue
    class Intangible < Thing
    end
  end
end

