# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/thing'

module Hotmeal
  module Schema
    # Intangible
    #
    # @see http://schema.org/Intangible
    #
    # Subtypes:
    # @see AlignmentObject
    # @see Audience
    # @see Brand
    # @see Demand
    # @see Enumeration
    # @see JobPosting
    # @see Language
    # @see Offer
    # @see Quantity
    # @see Rating
    # @see StructuredValue
    class Intangible < Thing
    end
  end
end

