# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/action'

module Hotmeal
  module Schema
    # Interact Action
    #
    # @see http://schema.org/InteractAction
    #
    # Subtypes:
    # @see BefriendAction
    # @see CommunicateAction
    # @see FollowAction
    # @see JoinAction
    # @see LeaveAction
    # @see MarryAction
    # @see RegisterAction
    # @see SubscribeAction
    # @see UnRegisterAction
    class InteractAction < Action
    end
  end
end

