# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/enumeration'

module Hotmeal
  module Schema
    # Item Availability
    #
    # @see http://schema.org/ItemAvailability
    class ItemAvailability < Enumeration
    end
  end
end
