# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/creative_work'

module Hotmeal
  module Schema
    # Item List
    #
    # @see http://schema.org/ItemList
    class ItemList < CreativeWork
      # A single list item.
      property :item_list_element, class_name: 'Text', as: 'itemListElement', label: 'Item List Element'
      # Type of ordering (e.g. Ascending, Descending, Unordered).
      property :item_list_order, class_name: 'Text', as: 'itemListOrder', label: 'Item List Order'
    end
  end
end

