# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Item List
    #
    # A list of items of any sort—for example, Top 10 Movies About Weathermen, or Top 100 Party Songs. Not to be confused with HTML lists, which are often used only for formatting.
    # @see http://schema.org/ItemList
    class ItemList < CreativeWork
      # A single list item.
      property :item_list_element, class_name: 'Text', as: 'itemListElement', label: 'Item List Element'
      # Type of ordering (e.g. Ascending, Descending, Unordered).
      property :item_list_order, class_name: 'Text', as: 'itemListOrder', label: 'Item List Order'
    end
  end
end

