# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/web_page'

module Hotmeal
  module Schema
    # Item Page
    #
    # A page devoted to a single item, such as a particular product or hotel.
    # @see http://schema.org/ItemPage
    class ItemPage < WebPage
    end
  end
end

