# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/store'

module Hotmeal
  module Schema
    # Jewelry Store
    #
    # A jewelry store.
    # @see http://schema.org/JewelryStore
    class JewelryStore < Store
    end
  end
end

