# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/intangible'

module Hotmeal
  module Schema
    # Job Posting
    #
    # @see http://schema.org/JobPosting
    class JobPosting < Intangible
      # The base salary of the job.
      property :base_salary, class_name: 'Number', as: 'baseSalary', label: 'Base Salary'
      # Description of benefits associated with the job.
      property :benefits, class_name: 'Text', as: 'benefits', label: 'Benefits'
      # Publication date for the job posting.
      property :date_posted, class_name: 'Date', as: 'datePosted', label: 'Date Posted'
      # Educational background needed for the position.
      property :education_requirements, class_name: 'Text', as: 'educationRequirements', label: 'Education Requirements'
      # Type of employment (e.g. full-time, part-time, contract, temporary, seasonal, internship).
      property :employment_type, class_name: 'Text', as: 'employmentType', label: 'Employment Type'
      # Description of skills and experience needed for the position.
      property :experience_requirements, class_name: 'Text', as: 'experienceRequirements', label: 'Experience Requirements'
      # Organization offering the job position.
      property :hiring_organization, class_name: 'Organization', as: 'hiringOrganization', label: 'Hiring Organization'
      # Description of bonus and commission compensation aspects of the job.
      property :incentives, class_name: 'Text', as: 'incentives', label: 'Incentives'
      # The industry associated with the job position.
      property :industry, class_name: 'Text', as: 'industry', label: 'Industry'
      # A (typically single) geographic location associated with the job position.
      property :job_location, class_name: 'Place', as: 'jobLocation', label: 'Job Location'
      # Category or categories describing the job. Use BLS O*NET-SOC taxonomy: http://www.onetcenter.org/taxonomy.html. Ideally includes textual label and formal code, with the property repeated for each applicable value.
      property :occupational_category, class_name: 'Text', as: 'occupationalCategory', label: 'Occupational Category'
      # Specific qualifications required for this role.
      property :qualifications, class_name: 'Text', as: 'qualifications', label: 'Qualifications'
      # Responsibilities associated with this role.
      property :responsibilities, class_name: 'Text', as: 'responsibilities', label: 'Responsibilities'
      # The currency (coded using ISO 4217, http://en.wikipedia.org/wiki/ISO_4217 used for the main salary information in this job posting.
      property :salary_currency, class_name: 'Text', as: 'salaryCurrency', label: 'Salary Currency'
      # Skills required to fulfill this role.
      property :skills, class_name: 'Text', as: 'skills', label: 'Skills'
      # Any special commitments associated with this job posting. Valid entries include VeteranCommit, MilitarySpouseCommit, etc.
      property :special_commitments, class_name: 'Text', as: 'specialCommitments', label: 'Special Commitments'
      # The title of the job.
      property :title, class_name: 'Text', as: 'title', label: 'Title'
      # The typical working hours for this job (e.g. 1st shift, night shift, 8am-5pm).
      property :work_hours, class_name: 'Text', as: 'workHours', label: 'Work Hours'
    end
  end
end

