# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/anatomical_structure'

module Hotmeal
  module Schema
    # Joint
    #
    # @see http://schema.org/Joint
    class Joint < AnatomicalStructure
      # The biomechanical properties of the bone.
      property :biomechnical_class, class_name: 'Text', as: 'biomechnicalClass', label: 'Biomechnical Class'
      # The degree of mobility the joint allows.
      property :functional_class, class_name: 'Text', as: 'functionalClass', label: 'Functional Class'
      # The name given to how bone physically connects to each other.
      property :structural_class, class_name: 'Text', as: 'structuralClass', label: 'Structural Class'
    end
  end
end

