# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Landmarks or Historical Buildings
    #
    # An historical landmark or building.
    # @see http://schema.org/LandmarksOrHistoricalBuildings
    class LandmarksOrHistoricalBuildings < Place
    end
  end
end

