# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/place'

module Hotmeal
  module Schema
    # Landform
    #
    # @see http://schema.org/Landform
    #
    # Subtypes:
    # @see BodyOfWater
    # @see Continent
    # @see Mountain
    # @see Volcano
    class Landform < Place
    end
  end
end

