# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/place'

module Hotmeal
  module Schema
    # Landmarks or Historical Buildings
    #
    # @see http://schema.org/LandmarksOrHistoricalBuildings
    class LandmarksOrHistoricalBuildings < Place
    end
  end
end

