# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/intangible'

module Hotmeal
  module Schema
    # Language
    #
    # @see http://schema.org/Language
    class Language < Intangible
    end
  end
end

