# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Legislative Building
    #
    # A legislative building—for example, the state capitol.
    # @see http://schema.org/LegislativeBuilding
    class LegislativeBuilding < GovernmentBuilding
    end
  end
end

