# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/government_building'

module Hotmeal
  module Schema
    # Legislative Building
    #
    # @see http://schema.org/LegislativeBuilding
    class LegislativeBuilding < GovernmentBuilding
    end
  end
end

