# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Library
    #
    # A library.
    # @see http://schema.org/Library
    class Library < LocalBusiness
    end
  end
end

