# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Lifestyle Modification
    #
    # A process of care involving exercise, changes to diet, fitness routines, and other lifestyle changes aimed at improving a health condition.
    # @see http://schema.org/LifestyleModification
    #
    # Subtypes:
    # @see Diet
    # @see PhysicalActivity
    class LifestyleModification < MedicalTherapy
    end
  end
end

