# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_therapy'

module Hotmeal
  module Schema
    # Lifestyle Modification
    #
    # @see http://schema.org/LifestyleModification
    #
    # Subtypes:
    # @see Diet
    # @see PhysicalActivity
    class LifestyleModification < MedicalTherapy
    end
  end
end
