# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/anatomical_structure'

module Hotmeal
  module Schema
    # Ligament
    #
    # @see http://schema.org/Ligament
    class Ligament < AnatomicalStructure
    end
  end
end
