# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/react_action'

module Hotmeal
  module Schema
    # Like Action
    #
    # @see http://schema.org/LikeAction
    class LikeAction < ReactAction
    end
  end
end

