# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Liquor Store
    #
    # A liquor store.
    # @see http://schema.org/LiquorStore
    class LiquorStore < Store
    end
  end
end

