# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Literary Event
    #
    # Event type: Literary event.
    # @see http://schema.org/LiteraryEvent
    class LiteraryEvent < Event
    end
  end
end

