# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/organization'

module Hotmeal
  module Schema
    # Local Business
    #
    # A particular physical business or branch of an organization. Examples of LocalBusiness include a restaurant, a particular branch of a restaurant chain, a branch of a bank, a medical practice, a club, a bowling alley, etc.
    # @see http://schema.org/LocalBusiness
    #
    # Subtypes:
    # @see AnimalShelter
    # @see AutomotiveBusiness
    # @see ChildCare
    # @see DryCleaningOrLaundry
    # @see EmergencyService
    # @see EmploymentAgency
    # @see EntertainmentBusiness
    # @see FinancialService
    # @see FoodEstablishment
    # @see GovernmentOffice
    # @see HealthAndBeautyBusiness
    # @see HomeAndConstructionBusiness
    # @see InternetCafe
    # @see Library
    # @see LodgingBusiness
    # @see MedicalOrganization
    # @see ProfessionalService
    # @see RadioStation
    # @see RealEstateAgent
    # @see RecyclingCenter
    # @see SelfStorage
    # @see ShoppingCenter
    # @see SportsActivityLocation
    # @see Store
    # @see TelevisionStation
    # @see TouristInformationCenter
    # @see TravelAgency
    class LocalBusiness < Organization
      # The larger organization that this local business is a branch of, if any.
      property :branch_of, class_name: 'Organization', as: 'branchOf', label: 'Branch of'
      # The currency accepted (in ISO 4217 currency format).
      property :currencies_accepted, class_name: 'Text', as: 'currenciesAccepted', label: 'Currencies Accepted'
      # The opening hours for a business. Opening hours can be specified as a weekly time range, starting with days, then times per day. Multiple days can be listed with commas ',' separating each day. Day or time ranges are specified using a hyphen '-'.- Days are specified using the following two-letter combinations: Mo, Tu, We, Th, Fr, Sa, Su.- Times are specified using 24:00 time. For example, 3pm is specified as 15:00. - Here is an example: <time itemprop="openingHours" datetime="Tu,Th 16:00-20:00">Tuesdays and Thursdays 4-8pm</time>. - If a business is open 7 days a week, then it can be specified as <time itemprop="openingHours" datetime="Mo-Su">Monday through Sunday, all day</time>.
      property :opening_hours, class_name: 'Duration', as: 'openingHours', label: 'Opening Hours'
      # Cash, credit card, etc.
      property :payment_accepted, class_name: 'Text', as: 'paymentAccepted', label: 'Payment Accepted'
      # The price range of the business, for example $$$.
      property :price_range, class_name: 'Text', as: 'priceRange', label: 'Price Range'
    end
  end
end

