# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/delivery_method'

module Hotmeal
  module Schema
    # Locker Delivery
    #
    # @see http://schema.org/LockerDelivery
    class LockerDelivery < DeliveryMethod
    end
  end
end
