# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/professional_service'

module Hotmeal
  module Schema
    # Locksmith
    #
    # A locksmith.
    # @see http://schema.org/Locksmith
    class Locksmith < ProfessionalService
    end
  end
end

