# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/local_business'

module Hotmeal
  module Schema
    # Lodging Business
    #
    # @see http://schema.org/LodgingBusiness
    #
    # Subtypes:
    # @see BedAndBreakfast
    # @see Hostel
    # @see Hotel
    # @see Motel
    class LodgingBusiness < LocalBusiness
    end
  end
end
