# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Lodging Business
    #
    # A lodging business, such as a motel, hotel, or inn.
    # @see http://schema.org/LodgingBusiness
    #
    # Subtypes:
    # @see BedAndBreakfast
    # @see Hostel
    # @see Hotel
    # @see Motel
    class LodgingBusiness < LocalBusiness
    end
  end
end

