# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/creative_work'

module Hotmeal
  module Schema
    # Map
    #
    # @see http://schema.org/Map
    class Map < CreativeWork
    end
  end
end

