# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/interact_action'

module Hotmeal
  module Schema
    # Marry Action
    #
    # @see http://schema.org/MarryAction
    class MarryAction < InteractAction
    end
  end
end

