# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/quantity'

module Hotmeal
  module Schema
    # Mass
    #
    # Properties that take Mass as values are of the form '<Number> <Mass unit of measure>'. E.g., '7 kg'
    # @see http://schema.org/Mass
    class Mass < Quantity
    end
  end
end

