# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/dose_schedule'

module Hotmeal
  module Schema
    # Maximum Dose Schedule
    #
    # @see http://schema.org/MaximumDoseSchedule
    class MaximumDoseSchedule < DoseSchedule
    end
  end
end

