# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_entity'

module Hotmeal
  module Schema
    # Medical Contraindication
    #
    # @see http://schema.org/MedicalContraindication
    class MedicalContraindication < MedicalEntity
    end
  end
end

