# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Medical Code
    #
    # A code for a medical entity.
    # @see http://schema.org/MedicalCode
    class MedicalCode < MedicalIntangible
      # The actual code.
      property :code_value, class_name: 'Text', as: 'codeValue', label: 'Code Value'
      # The coding system, e.g. 'ICD-10'.
      property :coding_system, class_name: 'Text', as: 'codingSystem', label: 'Coding System'
    end
  end
end

