# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_risk_estimator'

module Hotmeal
  module Schema
    # Medical Risk Calculator
    #
    # @see http://schema.org/MedicalRiskCalculator
    class MedicalRiskCalculator < MedicalRiskEstimator
    end
  end
end

