# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_entity'

module Hotmeal
  module Schema
    # Medical Guideline
    #
    # @see http://schema.org/MedicalGuideline
    #
    # Subtypes:
    # @see MedicalGuidelineContraindication
    # @see MedicalGuidelineRecommendation
    class MedicalGuideline < MedicalEntity
      # Strength of evidence of the data used to formulate the guideline (enumerated).
      property :evidence_level, class_name: 'MedicalEvidenceLevel', as: 'evidenceLevel', label: 'Evidence Level'
      # Source of the data used to formulate the guidance, e.g. RCT, consensus opinion, etc.
      property :evidence_origin, class_name: 'Text', as: 'evidenceOrigin', label: 'Evidence Origin'
      # Date on which this guideline's recommendation was made.
      property :guideline_date, class_name: 'Date', as: 'guidelineDate', label: 'Guideline Date'
      # The medical conditions, treatments, etc. that are the subject of the guideline.
      property :guideline_subject, class_name: 'MedicalEntity', as: 'guidelineSubject', label: 'Guideline Subject'
    end
  end
end

