# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_entity'

module Hotmeal
  module Schema
    # Medical Device
    #
    # @see http://schema.org/MedicalDevice
    class MedicalDevice < MedicalEntity
      # A possible complication and/or side effect of this therapy. If it is known that an adverse outcome is serious (resulting in death, disability, or permanent damage; requiring hospitalization; or is otherwise life-threatening or requires immediate medical attention), tag it as a seriouseAdverseOutcome instead.
      property :adverse_outcome, class_name: 'MedicalEntity', as: 'adverseOutcome', label: 'Adverse Outcome'
      # A contraindication for this therapy.
      property :contraindication, class_name: 'MedicalContraindication', as: 'contraindication', label: 'Contraindication'
      # A factor that indicates use of this therapy for treatment and/or prevention of a condition, symptom, etc. For therapies such as drugs, indications can include both officially-approved indications as well as off-label uses. These can be distinguished by using the ApprovedIndication subtype of MedicalIndication.
      property :indication, class_name: 'MedicalIndication', as: 'indication', label: 'Indication'
      # A description of the postoperative procedures, care, and/or followups for this device.
      property :post_op, class_name: 'Text', as: 'postOp', label: 'Post Op'
      # A description of the workup, testing, and other preparations required before implanting this device.
      property :pre_op, class_name: 'Text', as: 'preOp', label: 'Pre Op'
      # A description of the procedure involved in setting up, using, and/or installing the device.
      property :procedure, class_name: 'Text', as: 'procedure', label: 'Procedure'
      # A goal towards an action is taken. Can be concrete or abstract.
      property :purpose, class_names: %w[Thing MedicalDevicePurpose], as: 'purpose', label: 'Purpose'
      # A possible serious complication and/or serious side effect of this therapy. Serious adverse outcomes include those that are life-threatening; result in death, disability, or permanent damage; require hospitalization or prolong existing hospitalization; cause congenital anomalies or birth defects; or jeopardize the patient and may require medical or surgical intervention to prevent one of the outcomes in this definition.
      property :serious_adverse_outcome, class_name: 'MedicalEntity', as: 'seriousAdverseOutcome', label: 'Serious Adverse Outcome'
    end
  end
end

