# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_guideline'

module Hotmeal
  module Schema
    # Medical Guideline Contraindication
    #
    # @see http://schema.org/MedicalGuidelineContraindication
    class MedicalGuidelineContraindication < MedicalGuideline
    end
  end
end

