# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_entity'

module Hotmeal
  module Schema
    # Medical Risk Estimator
    #
    # @see http://schema.org/MedicalRiskEstimator
    #
    # Subtypes:
    # @see MedicalRiskCalculator
    # @see MedicalRiskScore
    class MedicalRiskEstimator < MedicalEntity
      # The condition, complication, or symptom whose risk is being estimated.
      property :estimates_risk_of, class_name: 'MedicalEntity', as: 'estimatesRiskOf', label: 'Estimates Risk of'
      # A modifiable or non-modifiable risk factor included in the calculation, e.g. age, coexisting condition.
      property :included_risk_factor, class_name: 'MedicalRiskFactor', as: 'includedRiskFactor', label: 'Included Risk Factor'
    end
  end
end
