# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_enumeration'

module Hotmeal
  module Schema
    # Medical Study Status
    #
    # @see http://schema.org/MedicalStudyStatus
    class MedicalStudyStatus < MedicalEnumeration
    end
  end
end

