# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_organization'

module Hotmeal
  module Schema
    # Medical Clinic
    #
    # @see http://schema.org/MedicalClinic
    class MedicalClinic < MedicalOrganization
      # A medical service available from this provider.
      property :available_service, class_names: %w[MedicalTest MedicalProcedure MedicalTherapy], as: 'availableService', label: 'Available Service'
      # A medical specialty of the provider.
      property :medical_specialty, class_name: 'MedicalSpecialty', as: 'medicalSpecialty', label: 'Medical Specialty'
    end
  end
end

