# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_risk_estimator'

module Hotmeal
  module Schema
    # Medical Risk Score
    #
    # A simple system that adds up the number of risk factors to yield a score that is associated with prognosis, e.g. CHAD score, TIMI risk score.
    # @see http://schema.org/MedicalRiskScore
    class MedicalRiskScore < MedicalRiskEstimator
      # The algorithm or rules to follow to compute the score.
      property :algorithm, class_name: 'Text', as: 'algorithm', label: 'Algorithm'
    end
  end
end

