# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Medical Guideline Contraindication
    #
    # A guideline contraindication that designates a process as harmful and where quality of the data supporting the contraindication is sound.
    # @see http://schema.org/MedicalGuidelineContraindication
    class MedicalGuidelineContraindication < MedicalGuideline
    end
  end
end

