# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Medical Observational Study Design
    #
    # Design models for observational medical studies. Enumerated type.
    # @see http://schema.org/MedicalObservationalStudyDesign
    class MedicalObservationalStudyDesign < MedicalEnumeration
    end
  end
end

