# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Medical Study
    #
    # A medical study is an umbrella type covering all kinds of research studies relating to human medicine or health, including observational studies and interventional trials and registries, randomized, controlled or not. When the specific type of study is known, use one of the extensions of this type, such as MedicalTrial or MedicalObservationalStudy. Also, note that this type should be used to mark up data that describes the study itself; to tag an article that publishes the results of a study, use MedicalScholarlyArticle. Note: use the code property of MedicalEntity to store study IDs, e.g. clinicaltrials.gov ID.
    # @see http://schema.org/MedicalStudy
    #
    # Subtypes:
    # @see MedicalObservationalStudy
    # @see MedicalTrial
    class MedicalStudy < MedicalEntity
      # Expected or actual outcomes of the study.
      property :outcome, class_name: 'Text', as: 'outcome', label: 'Outcome'
      # Any characteristics of the population used in the study, e.g. 'males under 65'.
      property :population, class_name: 'Text', as: 'population', label: 'Population'
      # Sponsor of the study.
      property :sponsor, class_name: 'Organization', as: 'sponsor', label: 'Sponsor'
      # The status of the study (enumerated).
      property :status, class_name: 'MedicalStudyStatus', as: 'status', label: 'Status'
      # The location in which the study is taking/took place.
      property :study_location, class_name: 'AdministrativeArea', as: 'studyLocation', label: 'Study Location'
      # A subject of the study, i.e. one of the medical conditions, therapies, devices, drugs, etc. investigated by the study.
      property :study_subject, class_name: 'MedicalEntity', as: 'studySubject', label: 'Study Subject'
    end
  end
end

