# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_enumeration'

module Hotmeal
  module Schema
    # Medical Procedure Type
    #
    # An enumeration that describes different types of medical procedures.
    # @see http://schema.org/MedicalProcedureType
    class MedicalProcedureType < MedicalEnumeration
    end
  end
end

