# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_enumeration'

module Hotmeal
  module Schema
    # Medical Procedure Type
    #
    # @see http://schema.org/MedicalProcedureType
    class MedicalProcedureType < MedicalEnumeration
    end
  end
end
