# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Medical Indication
    #
    # A condition or factor that indicates use of a medical therapy, including signs, symptoms, risk factors, anatomical states, etc.
    # @see http://schema.org/MedicalIndication
    #
    # Subtypes:
    # @see ApprovedIndication
    # @see PreventionIndication
    # @see TreatmentIndication
    class MedicalIndication < MedicalEntity
    end
  end
end

