# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_sign_or_symptom'

module Hotmeal
  module Schema
    # Medical Symptom
    #
    # @see http://schema.org/MedicalSymptom
    class MedicalSymptom < MedicalSignOrSymptom
    end
  end
end

