# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Medical Symptom
    #
    # Any indication of the existence of a medical condition or disease that is apparent to the patient.
    # @see http://schema.org/MedicalSymptom
    class MedicalSymptom < MedicalSignOrSymptom
    end
  end
end

