# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Medical Trial
    #
    # A medical trial is a type of medical study that uses scientific process used to compare the safety and efficacy of medical therapies or medical procedures. In general, medical trials are controlled and subjects are allocated at random to the different treatment and/or control groups.
    # @see http://schema.org/MedicalTrial
    class MedicalTrial < MedicalStudy
      # The phase of the trial.
      property :phase, class_name: 'Text', as: 'phase', label: 'Phase'
      # Specifics about the trial design (enumerated).
      property :trial_design, class_name: 'MedicalTrialDesign', as: 'trialDesign', label: 'Trial Design'
    end
  end
end

