# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_risk_estimator'

module Hotmeal
  module Schema
    # Medical Risk Calculator
    #
    # A complex mathematical calculation requiring an online calculator, used to assess prognosis. Note: use the url property of Thing to record any URLs for online calculators.
    # @see http://schema.org/MedicalRiskCalculator
    class MedicalRiskCalculator < MedicalRiskEstimator
    end
  end
end

