# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_enumeration'

module Hotmeal
  module Schema
    # Medical Device Purpose
    #
    # @see http://schema.org/MedicalDevicePurpose
    class MedicalDevicePurpose < MedicalEnumeration
    end
  end
end

