# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Medical Sign
    #
    # Any physical manifestation of a person's medical condition discoverable by objective diagnostic tests or physical examination.
    # @see http://schema.org/MedicalSign
    class MedicalSign < MedicalSignOrSymptom
      # A physical examination that can identify this sign.
      property :identifying_exam, class_name: 'PhysicalExam', as: 'identifyingExam', label: 'Identifying Exam'
      # A diagnostic test that can identify this sign.
      property :identifying_test, class_name: 'MedicalTest', as: 'identifyingTest', label: 'Identifying Test'
    end
  end
end

