# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/scholarly_article'

module Hotmeal
  module Schema
    # Medical Scholarly Article
    #
    # @see http://schema.org/MedicalScholarlyArticle
    class MedicalScholarlyArticle < ScholarlyArticle
      # The type of the medical article, taken from the US NLM MeSH publication type catalog.
      property :publication_type, class_name: 'Text', as: 'publicationType', label: 'Publication Type'
    end
  end
end

