# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_entity'

module Hotmeal
  module Schema
    # Medical Therapy
    #
    # @see http://schema.org/MedicalTherapy
    #
    # Subtypes:
    # @see DietarySupplement
    # @see Drug
    # @see DrugClass
    # @see LifestyleModification
    # @see PalliativeProcedure
    # @see PhysicalTherapy
    # @see PsychologicalTreatment
    # @see RadiationTherapy
    # @see TherapeuticProcedure
    class MedicalTherapy < MedicalEntity
      # A possible complication and/or side effect of this therapy. If it is known that an adverse outcome is serious (resulting in death, disability, or permanent damage; requiring hospitalization; or is otherwise life-threatening or requires immediate medical attention), tag it as a seriouseAdverseOutcome instead.
      property :adverse_outcome, class_name: 'MedicalEntity', as: 'adverseOutcome', label: 'Adverse Outcome'
      # A contraindication for this therapy.
      property :contraindication, class_name: 'MedicalContraindication', as: 'contraindication', label: 'Contraindication'
      # A therapy that duplicates or overlaps this one.
      property :duplicate_therapy, class_name: 'MedicalTherapy', as: 'duplicateTherapy', label: 'Duplicate Therapy'
      # A factor that indicates use of this therapy for treatment and/or prevention of a condition, symptom, etc. For therapies such as drugs, indications can include both officially-approved indications as well as off-label uses. These can be distinguished by using the ApprovedIndication subtype of MedicalIndication.
      property :indication, class_name: 'MedicalIndication', as: 'indication', label: 'Indication'
      # A possible serious complication and/or serious side effect of this therapy. Serious adverse outcomes include those that are life-threatening; result in death, disability, or permanent damage; require hospitalization or prolong existing hospitalization; cause congenital anomalies or birth defects; or jeopardize the patient and may require medical or surgical intervention to prevent one of the outcomes in this definition.
      property :serious_adverse_outcome, class_name: 'MedicalEntity', as: 'seriousAdverseOutcome', label: 'Serious Adverse Outcome'
    end
  end
end

