# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_enumeration'

module Hotmeal
  module Schema
    # Medical Imaging Technique
    #
    # Any medical imaging modality typically used for diagnostic purposes. Enumerated type.
    # @see http://schema.org/MedicalImagingTechnique
    class MedicalImagingTechnique < MedicalEnumeration
    end
  end
end

