# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_risk_estimator'

module Hotmeal
  module Schema
    # Medical Risk Score
    #
    # @see http://schema.org/MedicalRiskScore
    class MedicalRiskScore < MedicalRiskEstimator
      # The algorithm or rules to follow to compute the score.
      property :algorithm, class_name: 'Text', as: 'algorithm', label: 'Algorithm'
    end
  end
end

