# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_intangible'

module Hotmeal
  module Schema
    # Medical Enumeration
    #
    # Enumerations related to health and the practice of medicine.
    # @see http://schema.org/MedicalEnumeration
    #
    # Subtypes:
    # @see DrugCostCategory
    # @see DrugPregnancyCategory
    # @see DrugPrescriptionStatus
    # @see InfectiousAgentClass
    # @see MedicalAudience
    # @see MedicalDevicePurpose
    # @see MedicalEvidenceLevel
    # @see MedicalImagingTechnique
    # @see MedicalObservationalStudyDesign
    # @see MedicalProcedureType
    # @see MedicalSpecialty
    # @see MedicalStudyStatus
    # @see MedicalTrialDesign
    # @see MedicineSystem
    # @see PhysicalActivityCategory
    # @see PhysicalExam
    class MedicalEnumeration < MedicalIntangible
    end
  end
end

