# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_entity'

module Hotmeal
  module Schema
    # Medical Intangible
    #
    # A utility class that serves as the umbrella for a number of 'intangible' things in the medical space.
    # @see http://schema.org/MedicalIntangible
    #
    # Subtypes:
    # @see DDxElement
    # @see DoseSchedule
    # @see DrugCost
    # @see DrugLegalStatus
    # @see DrugStrength
    # @see MedicalCode
    # @see MedicalConditionStage
    # @see MedicalEnumeration
    class MedicalIntangible < MedicalEntity
    end
  end
end

