# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/people_audience'

module Hotmeal
  module Schema
    # Medical Audience
    #
    # Target audiences for medical web pages. Enumerated type.
    # @see http://schema.org/MedicalAudience
    class MedicalAudience < PeopleAudience
    end
  end
end

