# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_enumeration'

module Hotmeal
  module Schema
    # Medical Evidence Level
    #
    # @see http://schema.org/MedicalEvidenceLevel
    class MedicalEvidenceLevel < MedicalEnumeration
    end
  end
end
