# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_study'

module Hotmeal
  module Schema
    # Medical Observational Study
    #
    # @see http://schema.org/MedicalObservationalStudy
    class MedicalObservationalStudy < MedicalStudy
      # Specifics about the observational study design (enumerated).
      property :study_design, class_name: 'MedicalObservationalStudyDesign', as: 'studyDesign', label: 'Study Design'
    end
  end
end

