# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/local_business'

module Hotmeal
  module Schema
    # Medical Organization
    #
    # @see http://schema.org/MedicalOrganization
    #
    # Subtypes:
    # @see Dentist
    # @see DiagnosticLab
    # @see Hospital
    # @see MedicalClinic
    # @see Optician
    # @see Pharmacy
    # @see Physician
    # @see VeterinaryCare
    class MedicalOrganization < LocalBusiness
    end
  end
end

