# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/people_audience'

module Hotmeal
  module Schema
    # Medical Audience
    #
    # @see http://schema.org/MedicalAudience
    class MedicalAudience < PeopleAudience
    end
  end
end
