# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_entity'

module Hotmeal
  module Schema
    # Medical Study
    #
    # @see http://schema.org/MedicalStudy
    #
    # Subtypes:
    # @see MedicalObservationalStudy
    # @see MedicalTrial
    class MedicalStudy < MedicalEntity
      # Expected or actual outcomes of the study.
      property :outcome, class_name: 'Text', as: 'outcome', label: 'Outcome'
      # Any characteristics of the population used in the study, e.g. 'males under 65'.
      property :population, class_name: 'Text', as: 'population', label: 'Population'
      # Sponsor of the study.
      property :sponsor, class_name: 'Organization', as: 'sponsor', label: 'Sponsor'
      # The status of the study (enumerated).
      property :status, class_name: 'MedicalStudyStatus', as: 'status', label: 'Status'
      # The location in which the study is taking/took place.
      property :study_location, class_name: 'AdministrativeArea', as: 'studyLocation', label: 'Study Location'
      # A subject of the study, i.e. one of the medical conditions, therapies, devices, drugs, etc. investigated by the study.
      property :study_subject, class_name: 'MedicalEntity', as: 'studySubject', label: 'Study Subject'
    end
  end
end

