# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/thing'

module Hotmeal
  module Schema
    # Medical Entity
    #
    # @see http://schema.org/MedicalEntity
    #
    # Subtypes:
    # @see AnatomicalStructure
    # @see AnatomicalSystem
    # @see MedicalCause
    # @see MedicalCondition
    # @see MedicalContraindication
    # @see MedicalDevice
    # @see MedicalGuideline
    # @see MedicalIndication
    # @see MedicalIntangible
    # @see MedicalProcedure
    # @see MedicalRiskEstimator
    # @see MedicalRiskFactor
    # @see MedicalSignOrSymptom
    # @see MedicalStudy
    # @see MedicalTest
    # @see MedicalTherapy
    # @see SuperficialAnatomy
    class MedicalEntity < Thing
      # A medical code for the entity, taken from a controlled vocabulary or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
      property :code, class_name: 'MedicalCode', as: 'code', label: 'Code'
      # A medical guideline related to this entity.
      property :guideline, class_name: 'MedicalGuideline', as: 'guideline', label: 'Guideline'
      # The system of medicine that includes this MedicalEntity, for example 'evidence-based', 'homeopathic', 'chiropractic', etc.
      property :medicine_system, class_name: 'MedicineSystem', as: 'medicineSystem', label: 'Medicine System'
      # If applicable, the organization that officially recognizes this entity as part of its endorsed system of medicine.
      property :recognizing_authority, class_name: 'Organization', as: 'recognizingAuthority', label: 'Recognizing Authority'
      # If applicable, a medical specialty in which this entity is relevant.
      property :relevant_specialty, class_name: 'MedicalSpecialty', as: 'relevantSpecialty', label: 'Relevant Specialty'
      # A medical study or trial related to this entity.
      property :study, class_name: 'MedicalStudy', as: 'study', label: 'Study'
    end
  end
end
