# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/educational_organization'

module Hotmeal
  module Schema
    # Middle School
    #
    # A middle school.
    # @see http://schema.org/MiddleSchool
    class MiddleSchool < EducationalOrganization
    end
  end
end

