# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Motel
    #
    # A motel.
    # @see http://schema.org/Motel
    class Motel < LodgingBusiness
    end
  end
end

