# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Motorcycle Dealer
    #
    # A motorcycle dealer.
    # @see http://schema.org/MotorcycleDealer
    class MotorcycleDealer < AutomotiveBusiness
    end
  end
end

