# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/landform'

module Hotmeal
  module Schema
    # Mountain
    #
    # A mountain, like Mount Whitney or Mount Everest
    # @see http://schema.org/Mountain
    class Mountain < Landform
    end
  end
end

