# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/home_and_construction_business'

module Hotmeal
  module Schema
    # Moving Company
    #
    # A moving company.
    # @see http://schema.org/MovingCompany
    class MovingCompany < HomeAndConstructionBusiness
    end
  end
end

