# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/civic_structure'

module Hotmeal
  module Schema
    # Museum
    #
    # @see http://schema.org/Museum
    class Museum < CivicStructure
    end
  end
end
