# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/event'

module Hotmeal
  module Schema
    # Music Event
    #
    # @see http://schema.org/MusicEvent
    class MusicEvent < Event
    end
  end
end
