# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/civic_structure'

module Hotmeal
  module Schema
    # Music Venue
    #
    # A music venue.
    # @see http://schema.org/MusicVenue
    class MusicVenue < CivicStructure
    end
  end
end

