# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/music_playlist'

module Hotmeal
  module Schema
    # Music Album
    #
    # @see http://schema.org/MusicAlbum
    class MusicAlbum < MusicPlaylist
      # The artist that performed this album or recording.
      property :by_artist, class_name: 'MusicGroup', as: 'byArtist', label: 'By Artist'
    end
  end
end

