# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/event'

module Hotmeal
  module Schema
    # Music Event
    #
    # Event type: Music event.
    # @see http://schema.org/MusicEvent
    class MusicEvent < Event
    end
  end
end

