# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/civic_structure'

module Hotmeal
  module Schema
    # Music Venue
    #
    # @see http://schema.org/MusicVenue
    class MusicVenue < CivicStructure
    end
  end
end

