# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/creative_work'

module Hotmeal
  module Schema
    # Music Playlist
    #
    # @see http://schema.org/MusicPlaylist
    #
    # Subtypes:
    # @see MusicAlbum
    class MusicPlaylist < CreativeWork
      # The number of tracks in this album or playlist.
      property :num_tracks, class_name: 'Integer', as: 'numTracks', label: 'Num Tracks'
      # A music recording (track)—usually a single song.
      property :track, class_name: 'MusicRecording', as: 'track', label: 'Track'
      # A music recording (track)—usually a single song (legacy spelling; see singular form, track).
      property :tracks, class_name: 'MusicRecording', as: 'tracks', label: 'Tracks'
    end
  end
end

