# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/media_object'

module Hotmeal
  module Schema
    # Music Video Object
    #
    # @see http://schema.org/MusicVideoObject
    class MusicVideoObject < MediaObject
    end
  end
end

