# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Nail Salon
    #
    # A nail salon.
    # @see http://schema.org/NailSalon
    class NailSalon < HealthAndBeautyBusiness
    end
  end
end

