# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # NGO
    #
    # Organization: Non-governmental Organization.
    # @see http://schema.org/NGO
    class NGO < Organization
    end
  end
end

