# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/entertainment_business'

module Hotmeal
  module Schema
    # Night Club
    #
    # @see http://schema.org/NightClub
    class NightClub < EntertainmentBusiness
    end
  end
end

