# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Notary
    #
    # A notary.
    # @see http://schema.org/Notary
    class Notary < ProfessionalService
    end
  end
end

