# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/body_of_water'

module Hotmeal
  module Schema
    # Ocean Body of Water
    #
    # @see http://schema.org/OceanBodyOfWater
    class OceanBodyOfWater < BodyOfWater
    end
  end
end

