# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/enumeration'

module Hotmeal
  module Schema
    # Offer Item Condition
    #
    # @see http://schema.org/OfferItemCondition
    class OfferItemCondition < Enumeration
    end
  end
end
