# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Offer Item Condition
    #
    # A list of possible conditions for the item for sale.
    # @see http://schema.org/OfferItemCondition
    class OfferItemCondition < Enumeration
    end
  end
end

