# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/publication_event'

module Hotmeal
  module Schema
    # On Demand Event
    #
    # @see http://schema.org/OnDemandEvent
    class OnDemandEvent < PublicationEvent
    end
  end
end

