# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/delivery_method'

module Hotmeal
  module Schema
    # On Site Pickup
    #
    # @see http://schema.org/OnSitePickup
    class OnSitePickup < DeliveryMethod
    end
  end
end

