# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_organization'

module Hotmeal
  module Schema
    # Optician
    #
    # @see http://schema.org/Optician
    class Optician < MedicalOrganization
    end
  end
end

