# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/creative_work'

module Hotmeal
  module Schema
    # Painting
    #
    # A painting.
    # @see http://schema.org/Painting
    class Painting < CreativeWork
    end
  end
end

