# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_procedure'

module Hotmeal
  module Schema
    # Palliative Procedure
    #
    # @see http://schema.org/PalliativeProcedure
    class PalliativeProcedure < MedicalProcedure
    end
  end
end

