# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_procedure'

module Hotmeal
  module Schema
    # Palliative Procedure
    #
    # A medical procedure intended primarly for palliative purposes, aimed at relieving the symptoms of an underlying health condition.
    # @see http://schema.org/PalliativeProcedure
    class PalliativeProcedure < MedicalProcedure
    end
  end
end

