# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/delivery_method'

module Hotmeal
  module Schema
    # Parcel Service
    #
    # A private parcel service as the delivery mode available for a certain offer.
    # 
    # Commonly used values:
    # 
    # http://purl.org/goodrelations/v1#DHL
    # http://purl.org/goodrelations/v1#FederalExpress
    # http://purl.org/goodrelations/v1#UPS
    # @see http://schema.org/ParcelService
    class ParcelService < DeliveryMethod
    end
  end
end

