# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Parent Audience
    #
    # A set of characteristics describing parents, who can be interested in viewing some content
    # @see http://schema.org/ParentAudience
    class ParentAudience < PeopleAudience
      # Maximal age of the child
      property :child_max_age, class_name: 'Number', as: 'childMaxAge', label: 'Child Max Age'
      # Minimal age of the child
      property :child_min_age, class_name: 'Number', as: 'childMinAge', label: 'Child Min Age'
    end
  end
end

