# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Pathology Test
    #
    # A medical test performed by a laboratory that typically involves examination of a tissue sample by a pathologist.
    # @see http://schema.org/PathologyTest
    class PathologyTest < MedicalTest
      # The type of tissue sample required for the test.
      property :tissue_sample, class_name: 'Text', as: 'tissueSample', label: 'Tissue Sample'
    end
  end
end

