# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/store'

module Hotmeal
  module Schema
    # Pawn Shop
    #
    # @see http://schema.org/PawnShop
    class PawnShop < Store
    end
  end
end

