# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Pawn Shop
    #
    # A pawnstore.
    # @see http://schema.org/PawnShop
    class PawnShop < Store
    end
  end
end

