# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/enumeration'

module Hotmeal
  module Schema
    # Payment Method
    #
    # @see http://schema.org/PaymentMethod
    #
    # Subtypes:
    # @see CreditCard
    class PaymentMethod < Enumeration
    end
  end
end

