# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/play_action'

module Hotmeal
  module Schema
    # Perform Action
    #
    # @see http://schema.org/PerformAction
    class PerformAction < PlayAction
      # A sub property of location. The entertainment business where the action occurred.
      property :entertainment_business, class_name: 'EntertainmentBusiness', as: 'entertainmentBusiness', label: 'Entertainment Business'
    end
  end
end

