# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/organization'

module Hotmeal
  module Schema
    # Performing Group
    #
    # @see http://schema.org/PerformingGroup
    #
    # Subtypes:
    # @see DanceGroup
    # @see MusicGroup
    # @see TheaterGroup
    class PerformingGroup < Organization
    end
  end
end

