# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Performing Group
    #
    # A performance group, such as a band, an orchestra, or a circus.
    # @see http://schema.org/PerformingGroup
    #
    # Subtypes:
    # @see DanceGroup
    # @see MusicGroup
    # @see TheaterGroup
    class PerformingGroup < Organization
    end
  end
end

