# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Performing Arts Theater
    #
    # A theatre or other performing art center.
    # @see http://schema.org/PerformingArtsTheater
    class PerformingArtsTheater < CivicStructure
    end
  end
end

