# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/thing'

module Hotmeal
  module Schema
    # Person
    #
    # @see http://schema.org/Person
    class Person < Thing
      # An additional name for a Person, can be used for a middle name.
      property :additional_name, class_name: 'Text', as: 'additionalName', label: 'Additional Name'
      # Physical address of the item.
      property :address, class_name: 'PostalAddress', as: 'address', label: 'Address'
      # An organization that this person is affiliated with. For example, a school/university, a club, or a team.
      property :affiliation, class_name: 'Organization', as: 'affiliation', label: 'Affiliation'
      # An educational organizations that the person is an alumni of.
      property :alumni_of, class_name: 'EducationalOrganization', as: 'alumniOf', label: 'Alumni of'
      # An award won by this person or for this creative work.
      property :award, class_name: 'Text', as: 'award', label: 'Award'
      # Awards won by this person or for this creative work. (legacy spelling; see singular form, award)
      property :awards, class_name: 'Text', as: 'awards', label: 'Awards'
      # Date of birth.
      property :birth_date, class_name: 'Date', as: 'birthDate', label: 'Birth Date'
      # The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.
      property :brand, class_names: %w[Organization Brand], as: 'brand', label: 'Brand'
      # A child of the person.
      property :children, class_name: 'Person', as: 'children', label: 'Children'
      # A colleague of the person.
      property :colleague, class_name: 'Person', as: 'colleague', label: 'Colleague'
      # A colleague of the person (legacy spelling; see singular form, colleague).
      property :colleagues, class_name: 'Person', as: 'colleagues', label: 'Colleagues'
      # A contact point for a person or organization.
      property :contact_point, class_name: 'ContactPoint', as: 'contactPoint', label: 'Contact Point'
      # A contact point for a person or organization (legacy spelling; see singular form, contactPoint).
      property :contact_points, class_name: 'ContactPoint', as: 'contactPoints', label: 'Contact Points'
      # Date of death.
      property :death_date, class_name: 'Date', as: 'deathDate', label: 'Death Date'
      # The Dun & Bradstreet DUNS number for identifying an organization or business person.
      property :duns, class_name: 'Text', as: 'duns', label: 'Duns'
      # Email address.
      property :email, class_name: 'Text', as: 'email', label: 'Email'
      # Family name. In the U.S., the last name of an Person. This can be used along with givenName instead of the Name property.
      property :family_name, class_name: 'Text', as: 'familyName', label: 'Family Name'
      # The fax number.
      property :fax_number, class_name: 'Text', as: 'faxNumber', label: 'Fax Number'
      # The most generic uni-directional social relation.
      property :follows, class_name: 'Person', as: 'follows', label: 'Follows'
      # Gender of the person.
      property :gender, class_name: 'Text', as: 'gender', label: 'Gender'
      # Given name. In the U.S., the first name of a Person. This can be used along with familyName instead of the Name property.
      property :given_name, class_name: 'Text', as: 'givenName', label: 'Given Name'
      # The Global Location Number (GLN, sometimes also referred to as International Location Number or ILN) of the respective organization, person, or place. The GLN is a 13-digit number used to identify parties and physical locations.
      property :global_location_number, class_name: 'Text', as: 'globalLocationNumber', label: 'Global Location Number'
      # Points-of-Sales operated by the organization or person.
      property :has_pos, class_name: 'Place', as: 'hasPOS', label: 'Has POS'
      # A contact location for a person's residence.
      property :home_location, class_names: %w[ContactPoint Place], as: 'homeLocation', label: 'Home Location'
      # An honorific prefix preceding a Person's name such as Dr/Mrs/Mr.
      property :honorific_prefix, class_name: 'Text', as: 'honorificPrefix', label: 'Honorific Prefix'
      # An honorific suffix preceding a Person's name such as M.D. /PhD/MSCSW.
      property :honorific_suffix, class_name: 'Text', as: 'honorificSuffix', label: 'Honorific Suffix'
      # A count of a specific user interactions with this item—for example, 20 UserLikes, 5 UserComments, or 300 UserDownloads. The user interaction type should be one of the sub types of UserInteraction.
      property :interaction_count, class_name: 'Text', as: 'interactionCount', label: 'Interaction Count'
      # The International Standard of Industrial Classification of All Economic Activities (ISIC), Revision 4 code for a particular organization, business person, or place.
      property :isic_v4, class_name: 'Text', as: 'isicV4', label: 'Isic V4'
      # The job title of the person (for example, Financial Manager).
      property :job_title, class_name: 'Text', as: 'jobTitle', label: 'Job Title'
      # The most generic bi-directional social/work relation.
      property :knows, class_name: 'Person', as: 'knows', label: 'Knows'
      # A pointer to products or services offered by the organization or person.
      property :makes_offer, class_name: 'Offer', as: 'makesOffer', label: 'Makes Offer'
      # An organization to which the person belongs.
      property :member_of, class_name: 'Organization', as: 'memberOf', label: 'Member of'
      # The North American Industry Classification System (NAICS) code for a particular organization or business person.
      property :naics, class_name: 'Text', as: 'naics', label: 'Naics'
      # Nationality of the person.
      property :nationality, class_name: 'Country', as: 'nationality', label: 'Nationality'
      # Products owned by the organization or person.
      property :owns, class_names: %w[OwnershipInfo Product], as: 'owns', label: 'Owns'
      # A parent of this person.
      property :parent, class_name: 'Person', as: 'parent', label: 'Parent'
      # A parents of the person (legacy spelling; see singular form, parent).
      property :parents, class_name: 'Person', as: 'parents', label: 'Parents'
      # Event that this person is a performer or participant in.
      property :performer_in, class_name: 'Event', as: 'performerIn', label: 'Performer in'
      # The most generic familial relation.
      property :related_to, class_name: 'Person', as: 'relatedTo', label: 'Related to'
      # A pointer to products or services sought by the organization or person (demand).
      property :seeks, class_name: 'Demand', as: 'seeks', label: 'Seeks'
      # A sibling of the person.
      property :sibling, class_name: 'Person', as: 'sibling', label: 'Sibling'
      # A sibling of the person (legacy spelling; see singular form, sibling).
      property :siblings, class_name: 'Person', as: 'siblings', label: 'Siblings'
      # The person's spouse.
      property :spouse, class_name: 'Person', as: 'spouse', label: 'Spouse'
      # The Tax / Fiscal ID of the organization or person, e.g. the TIN in the US or the CIF/NIF in Spain.
      property :tax_id, class_name: 'Text', as: 'taxID', label: 'Tax ID'
      # The telephone number.
      property :telephone, class_name: 'Text', as: 'telephone', label: 'Telephone'
      # The Value-added Tax ID of the organisation or person.
      property :vat_id, class_name: 'Text', as: 'vatID', label: 'Vat ID'
      # A contact location for a person's place of work.
      property :work_location, class_names: %w[ContactPoint Place], as: 'workLocation', label: 'Work Location'
      # Organizations that the person works for.
      property :works_for, class_name: 'Organization', as: 'worksFor', label: 'Works for'
    end
  end
end

