# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Pet Store
    #
    # A pet store.
    # @see http://schema.org/PetStore
    class PetStore < Store
    end
  end
end

