# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_organization'

module Hotmeal
  module Schema
    # Pharmacy
    #
    # A pharmacy or drugstore.
    # @see http://schema.org/Pharmacy
    class Pharmacy < MedicalOrganization
    end
  end
end

