# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/create_action'

module Hotmeal
  module Schema
    # Photograph Action
    #
    # @see http://schema.org/PhotographAction
    class PhotographAction < CreateAction
    end
  end
end

