# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Photograph
    #
    # A photograph.
    # @see http://schema.org/Photograph
    class Photograph < CreativeWork
    end
  end
end

