# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_enumeration'

module Hotmeal
  module Schema
    # Physical Activity Category
    #
    # @see http://schema.org/PhysicalActivityCategory
    class PhysicalActivityCategory < MedicalEnumeration
    end
  end
end

