# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_organization'

module Hotmeal
  module Schema
    # Physician
    #
    # @see http://schema.org/Physician
    class Physician < MedicalOrganization
      # A medical service available from this provider.
      property :available_service, class_names: %w[MedicalTest MedicalProcedure MedicalTherapy], as: 'availableService', label: 'Available Service'
      # A hospital with which the physician or office is affiliated.
      property :hospital_affiliation, class_name: 'Hospital', as: 'hospitalAffiliation', label: 'Hospital Affiliation'
      # A medical specialty of the provider.
      property :medical_specialty, class_name: 'MedicalSpecialty', as: 'medicalSpecialty', label: 'Medical Specialty'
    end
  end
end

