# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_enumeration'

module Hotmeal
  module Schema
    # Physical Exam
    #
    # A type of physical examination of a patient performed by a physician. Enumerated type.
    # @see http://schema.org/PhysicalExam
    class PhysicalExam < MedicalEnumeration
    end
  end
end

