# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_therapy'

module Hotmeal
  module Schema
    # Physical Therapy
    #
    # A process of progressive physical care and rehabilitation aimed at improving a health condition.
    # @see http://schema.org/PhysicalTherapy
    class PhysicalTherapy < MedicalTherapy
    end
  end
end

