# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/civic_structure'

module Hotmeal
  module Schema
    # Place of Worship
    #
    # Place of worship, such as a church, synagogue, or mosque.
    # @see http://schema.org/PlaceOfWorship
    #
    # Subtypes:
    # @see BuddhistTemple
    # @see CatholicChurch
    # @see Church
    # @see HinduTemple
    # @see Mosque
    # @see Synagogue
    class PlaceOfWorship < CivicStructure
    end
  end
end

