# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/organize_action'

module Hotmeal
  module Schema
    # Plan Action
    #
    # @see http://schema.org/PlanAction
    #
    # Subtypes:
    # @see CancelAction
    # @see ReserveAction
    # @see ScheduleAction
    class PlanAction < OrganizeAction
      # The time the object is scheduled to.
      property :scheduled_time, class_name: 'DateTime', as: 'scheduledTime', label: 'Scheduled Time'
    end
  end
end

