# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Playground
    #
    # A playground.
    # @see http://schema.org/Playground
    class Playground < CivicStructure
    end
  end
end

