# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/civic_structure'

module Hotmeal
  module Schema
    # Playground
    #
    # @see http://schema.org/Playground
    class Playground < CivicStructure
    end
  end
end
