# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Plumber
    #
    # A plumbing service.
    # @see http://schema.org/Plumber
    class Plumber < ProfessionalService
    end
  end
end

