# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/professional_service'

module Hotmeal
  module Schema
    # Plumber
    #
    # @see http://schema.org/Plumber
    class Plumber < ProfessionalService
    end
  end
end

