# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Police Station
    #
    # A police station.
    # @see http://schema.org/PoliceStation
    class PoliceStation < CivicStructure
    end
  end
end

