# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Pond
    #
    # A pond
    # @see http://schema.org/Pond
    class Pond < BodyOfWater
    end
  end
end

