# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/contact_point'

module Hotmeal
  module Schema
    # Postal Address
    #
    # The mailing address.
    # @see http://schema.org/PostalAddress
    class PostalAddress < ContactPoint
      # The country. For example, USA. You can also provide the two-letter ISO 3166-1 alpha-2 country code.
      property :address_country, class_name: 'Country', as: 'addressCountry', label: 'Address Country'
      # The locality. For example, Mountain View.
      property :address_locality, class_name: 'Text', as: 'addressLocality', label: 'Address Locality'
      # The region. For example, CA.
      property :address_region, class_name: 'Text', as: 'addressRegion', label: 'Address Region'
      # The postal code. For example, 94043.
      property :postal_code, class_name: 'Text', as: 'postalCode', label: 'Postal Code'
      # The post offce box number for PO box addresses.
      property :post_office_box_number, class_name: 'Text', as: 'postOfficeBoxNumber', label: 'Post Office Box Number'
      # The street address. For example, 1600 Amphitheatre Pkwy.
      property :street_address, class_name: 'Text', as: 'streetAddress', label: 'Street Address'
    end
  end
end

