# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/government_office'

module Hotmeal
  module Schema
    # Post Office
    #
    # @see http://schema.org/PostOffice
    class PostOffice < GovernmentOffice
    end
  end
end

