# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Post Office
    #
    # A post office.
    # @see http://schema.org/PostOffice
    class PostOffice < GovernmentOffice
    end
  end
end

