# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Preschool
    #
    # A preschool.
    # @see http://schema.org/Preschool
    class Preschool < EducationalOrganization
    end
  end
end

