# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/educational_organization'

module Hotmeal
  module Schema
    # Preschool
    #
    # @see http://schema.org/Preschool
    class Preschool < EducationalOrganization
    end
  end
end

