# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_indication'

module Hotmeal
  module Schema
    # Prevention Indication
    #
    # @see http://schema.org/PreventionIndication
    class PreventionIndication < MedicalIndication
    end
  end
end
