# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Profile Page
    #
    # Web page type: Profile page.
    # @see http://schema.org/ProfilePage
    class ProfilePage < WebPage
    end
  end
end

