# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/local_business'

module Hotmeal
  module Schema
    # Professional Service
    #
    # Provider of professional services.
    # @see http://schema.org/ProfessionalService
    #
    # Subtypes:
    # @see AccountingService
    # @see Attorney
    # @see Dentist
    # @see Electrician
    # @see GeneralContractor
    # @see HousePainter
    # @see Locksmith
    # @see Notary
    # @see Plumber
    # @see RoofingContractor
    class ProfessionalService < LocalBusiness
    end
  end
end

