# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_therapy'

module Hotmeal
  module Schema
    # Psychological Treatment
    #
    # A process of care relying upon counseling, dialogue, communication, verbalization aimed at improving a mental health condition.
    # @see http://schema.org/PsychologicalTreatment
    class PsychologicalTreatment < MedicalTherapy
    end
  end
end

