# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_therapy'

module Hotmeal
  module Schema
    # Psychological Treatment
    #
    # @see http://schema.org/PsychologicalTreatment
    class PsychologicalTreatment < MedicalTherapy
    end
  end
end
