# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/sports_activity_location'

module Hotmeal
  module Schema
    # Public Swimming Pool
    #
    # @see http://schema.org/PublicSwimmingPool
    class PublicSwimmingPool < SportsActivityLocation
    end
  end
end
