# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/event'

module Hotmeal
  module Schema
    # Publication Event
    #
    # @see http://schema.org/PublicationEvent
    #
    # Subtypes:
    # @see BroadcastEvent
    # @see OnDemandEvent
    class PublicationEvent < Event
      # A flag to signal that the publication is accessible for free.
      property :free, class_name: 'Boolean', as: 'free', label: 'Free'
      # A broadcast service associated with the publication event
      property :published_on, class_name: 'BroadcastService', as: 'publishedOn', label: 'Published On'
    end
  end
end
