# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Public Swimming Pool
    #
    # A public swimming pool.
    # @see http://schema.org/PublicSwimmingPool
    class PublicSwimmingPool < SportsActivityLocation
    end
  end
end

