# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/enumeration'

module Hotmeal
  module Schema
    # Qualitative Value
    #
    # A predefined value for a product characteristic, e.g. the the power cord plug type "US" or the garment sizes "S", "M", "L", and "XL"
    # @see http://schema.org/QualitativeValue
    class QualitativeValue < Enumeration
      # This ordering relation for qualitative values indicates that the subject is equal to the object.
      property :equal, class_name: 'QualitativeValue', as: 'equal', label: 'Equal'
      # This ordering relation for qualitative values indicates that the subject is greater than the object.
      property :greater, class_name: 'QualitativeValue', as: 'greater', label: 'Greater'
      # This ordering relation for qualitative values indicates that the subject is greater than or equal to the object.
      property :greater_or_equal, class_name: 'QualitativeValue', as: 'greaterOrEqual', label: 'Greater or Equal'
      # This ordering relation for qualitative values indicates that the subject is lesser than the object.
      property :lesser, class_name: 'QualitativeValue', as: 'lesser', label: 'Lesser'
      # This ordering relation for qualitative values indicates that the subject is lesser than or equal to the object.
      property :lesser_or_equal, class_name: 'QualitativeValue', as: 'lesserOrEqual', label: 'Lesser or Equal'
      # This ordering relation for qualitative values indicates that the subject is not equal to the object.
      property :non_equal, class_name: 'QualitativeValue', as: 'nonEqual', label: 'Non Equal'
      # A pointer to a secondary value that provides additional information on the original value, e.g. a reference temperature.
      property :value_reference, class_names: %w[Enumeration StructuredValue], as: 'valueReference', label: 'Value Reference'
    end
  end
end

