# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/intangible'

module Hotmeal
  module Schema
    # Quantity
    #
    # Quantities such as distance, time, mass, weight, etc. Particular instances of say Mass are entities like '3 Kg' or '4 milligrams'.
    # @see http://schema.org/Quantity
    #
    # Subtypes:
    # @see Distance
    # @see Duration
    # @see Energy
    # @see Mass
    class Quantity < Intangible
    end
  end
end

