# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/structured_value'

module Hotmeal
  module Schema
    # Quantitative Value
    #
    # @see http://schema.org/QuantitativeValue
    class QuantitativeValue < StructuredValue
      # The upper of the product characteristic.
      property :max_value, class_name: 'Number', as: 'maxValue', label: 'Max Value'
      # The lower value of the product characteristic.
      property :min_value, class_name: 'Number', as: 'minValue', label: 'Min Value'
      # The unit of measurement given using the UN/CEFACT Common Code (3 characters).
      property :unit_code, class_name: 'Text', as: 'unitCode', label: 'Unit Code'
      # The value of the product characteristic.
      property :value, class_name: 'Number', as: 'value', label: 'Value'
      # A pointer to a secondary value that provides additional information on the original value, e.g. a reference temperature.
      property :value_reference, class_names: %w[Enumeration StructuredValue], as: 'valueReference', label: 'Value Reference'
    end
  end
end

