# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/intangible'

module Hotmeal
  module Schema
    # Quantity
    #
    # @see http://schema.org/Quantity
    #
    # Subtypes:
    # @see Distance
    # @see Duration
    # @see Energy
    # @see Mass
    class Quantity < Intangible
    end
  end
end
