# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/trade_action'

module Hotmeal
  module Schema
    # Quote Action
    #
    # @see http://schema.org/QuoteAction
    class QuoteAction < TradeAction
    end
  end
end

