# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Radio Station
    #
    # A radio station.
    # @see http://schema.org/RadioStation
    class RadioStation < LocalBusiness
    end
  end
end

