# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_therapy'

module Hotmeal
  module Schema
    # Radiation Therapy
    #
    # @see http://schema.org/RadiationTherapy
    class RadiationTherapy < MedicalTherapy
    end
  end
end

