# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/clip'

module Hotmeal
  module Schema
    # Radio Clip
    #
    # @see http://schema.org/RadioClip
    class RadioClip < Clip
    end
  end
end
