# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/local_business'

module Hotmeal
  module Schema
    # Radio Station
    #
    # @see http://schema.org/RadioStation
    class RadioStation < LocalBusiness
    end
  end
end

