# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/season'

module Hotmeal
  module Schema
    # Radio Season
    #
    # @see http://schema.org/RadioSeason
    class RadioSeason < Season
    end
  end
end
