# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Real Estate Agent
    #
    # A real-estate agent.
    # @see http://schema.org/RealEstateAgent
    class RealEstateAgent < LocalBusiness
    end
  end
end

