# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/creative_work'

module Hotmeal
  module Schema
    # Recipe
    #
    # A recipe.
    # @see http://schema.org/Recipe
    class Recipe < CreativeWork
      # The method of cooking, such as Frying, Steaming, ...
      property :cooking_method, class_name: 'Text', as: 'cookingMethod', label: 'Cooking Method'
      # The time it takes to actually cook the dish, in ISO 8601 duration format.
      property :cook_time, class_name: 'Duration', as: 'cookTime', label: 'Cook Time'
      # An ingredient used in the recipe.
      property :ingredients, class_name: 'Text', as: 'ingredients', label: 'Ingredients'
      # Nutrition information about the recipe.
      property :nutrition, class_name: 'NutritionInformation', as: 'nutrition', label: 'Nutrition'
      # The length of time it takes to prepare the recipe, in ISO 8601 duration format.
      property :prep_time, class_name: 'Duration', as: 'prepTime', label: 'Prep Time'
      # The category of the recipe—for example, appetizer, entree, etc.
      property :recipe_category, class_name: 'Text', as: 'recipeCategory', label: 'Recipe Category'
      # The cuisine of the recipe (for example, French or Ethopian).
      property :recipe_cuisine, class_name: 'Text', as: 'recipeCuisine', label: 'Recipe Cuisine'
      # The steps to make the dish.
      property :recipe_instructions, class_name: 'Text', as: 'recipeInstructions', label: 'Recipe Instructions'
      # The quantity produced by the recipe (for example, number of people served, number of servings, etc).
      property :recipe_yield, class_name: 'Text', as: 'recipeYield', label: 'Recipe Yield'
      # The total time it takes to prepare and cook the recipe, in ISO 8601 duration format.
      property :total_time, class_name: 'Duration', as: 'totalTime', label: 'Total Time'
    end
  end
end

