# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/dose_schedule'

module Hotmeal
  module Schema
    # Recommended Dose Schedule
    #
    # A recommended dosing schedule for a drug or supplement as prescribed or recommended by an authority or by the drug/supplement's manufacturer. Capture the recommending authority in the recognizingAuthority property of MedicalEntity.
    # @see http://schema.org/RecommendedDoseSchedule
    class RecommendedDoseSchedule < DoseSchedule
    end
  end
end

