# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/dose_schedule'

module Hotmeal
  module Schema
    # Recommended Dose Schedule
    #
    # @see http://schema.org/RecommendedDoseSchedule
    class RecommendedDoseSchedule < DoseSchedule
    end
  end
end

