# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/local_business'

module Hotmeal
  module Schema
    # Recycling Center
    #
    # @see http://schema.org/RecyclingCenter
    class RecyclingCenter < LocalBusiness
    end
  end
end
