# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/interact_action'

module Hotmeal
  module Schema
    # Register Action
    #
    # @see http://schema.org/RegisterAction
    class RegisterAction < InteractAction
    end
  end
end

