# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/allocate_action'

module Hotmeal
  module Schema
    # Reject Action
    #
    # @see http://schema.org/RejectAction
    class RejectAction < AllocateAction
    end
  end
end

