# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/dose_schedule'

module Hotmeal
  module Schema
    # Reported Dose Schedule
    #
    # A patient-reported or observed dosing schedule for a drug or supplement.
    # @see http://schema.org/ReportedDoseSchedule
    class ReportedDoseSchedule < DoseSchedule
    end
  end
end

