# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/place'

module Hotmeal
  module Schema
    # Residence
    #
    # @see http://schema.org/Residence
    #
    # Subtypes:
    # @see ApartmentComplex
    # @see GatedResidenceCommunity
    # @see SingleFamilyResidence
    class Residence < Place
    end
  end
end

