# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/food_establishment'

module Hotmeal
  module Schema
    # Restaurant
    #
    # A restaurant.
    # @see http://schema.org/Restaurant
    class Restaurant < FoodEstablishment
    end
  end
end

