# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Roofing Contractor
    #
    # A roofing contractor.
    # @see http://schema.org/RoofingContractor
    class RoofingContractor < ProfessionalService
    end
  end
end

