# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/inform_action'

module Hotmeal
  module Schema
    # Rsvp Action
    #
    # @see http://schema.org/RsvpAction
    class RsvpAction < InformAction
    end
  end
end

