# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/civic_structure'

module Hotmeal
  module Schema
    # RV Park
    #
    # @see http://schema.org/RVPark
    class RVPark < CivicStructure
    end
  end
end

