# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/event'

module Hotmeal
  module Schema
    # Sale Event
    #
    # Event type: Sales event.
    # @see http://schema.org/SaleEvent
    class SaleEvent < Event
    end
  end
end

