# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/plan_action'

module Hotmeal
  module Schema
    # Schedule Action
    #
    # @see http://schema.org/ScheduleAction
    class ScheduleAction < PlanAction
    end
  end
end

