# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/educational_organization'

module Hotmeal
  module Schema
    # School
    #
    # @see http://schema.org/School
    class School < EducationalOrganization
    end
  end
end

