# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/article'

module Hotmeal
  module Schema
    # Scholarly Article
    #
    # @see http://schema.org/ScholarlyArticle
    #
    # Subtypes:
    # @see MedicalScholarlyArticle
    class ScholarlyArticle < Article
    end
  end
end

