# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/creative_work'

module Hotmeal
  module Schema
    # Sculpture
    #
    # A piece of sculpture.
    # @see http://schema.org/Sculpture
    class Sculpture < CreativeWork
    end
  end
end

