# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Sea Body of Water
    #
    # A sea (for example, the Caspian sea).
    # @see http://schema.org/SeaBodyOfWater
    class SeaBodyOfWater < BodyOfWater
    end
  end
end

