# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/action'

module Hotmeal
  module Schema
    # Search Action
    #
    # @see http://schema.org/SearchAction
    class SearchAction < Action
      # A sub property of instrument. The query used on this action.
      property :query, class_names: %w[Class Text], as: 'query', label: 'Query'
    end
  end
end

