# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Self Storage
    #
    # Self-storage facility.
    # @see http://schema.org/SelfStorage
    class SelfStorage < LocalBusiness
    end
  end
end

