# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/trade_action'

module Hotmeal
  module Schema
    # Sell Action
    #
    # @see http://schema.org/SellAction
    class SellAction < TradeAction
      # A sub property of participant. The participant/person/organization that bought the object.
      property :buyer, class_name: 'Person', as: 'buyer', label: 'Buyer'
      # The warranty promise(s) included in the offer.
      property :warranty_promise, class_name: 'WarrantyPromise', as: 'warrantyPromise', label: 'Warranty Promise'
    end
  end
end

