# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/transfer_action'

module Hotmeal
  module Schema
    # Send Action
    #
    # @see http://schema.org/SendAction
    class SendAction < TransferAction
      # A sub property of instrument. The method of delivery
      property :delivery_method, class_name: 'DeliveryMethod', as: 'deliveryMethod', label: 'Delivery Method'
      # A sub property of participant. The participant who is at the receiving end of the action.
      property :recipient, class_names: %w(Organization Audience Person), as: 'recipient', label: 'Recipient'
    end
  end
end
