# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/creative_work'

module Hotmeal
  module Schema
    # Series
    #
    # @see http://schema.org/Series
    #
    # Subtypes:
    # @see RadioSeries
    # @see TVSeries
    class Series < CreativeWork
      # A cast member of the movie, tv/radio series, season, episode, or video.
      property :actor, class_name: 'Person', as: 'actor', label: 'Actor'
      # A cast member of the movie, tv/radio series, season, episode, or video. (legacy spelling; see singular form, actor)
      property :actors, class_name: 'Person', as: 'actors', label: 'Actors'
      # The director of the movie, tv/radio episode or series.
      property :director, class_name: 'Person', as: 'director', label: 'Director'
      # The director of the movie, tv/radio episode or series. (legacy spelling; see singular form, director)
      property :directors, class_name: 'Person', as: 'directors', label: 'Directors'
      # The end date and time of the event or item (in ISO 8601 date format).
      property :end_date, class_name: 'Date', as: 'endDate', label: 'End Date'
      # An episode of a TV/radio series or season
      property :episode, class_name: 'Episode', as: 'episode', label: 'Episode'
      # An episode of a TV/radio series or season (legacy spelling; see singular form, episode)
      property :episodes, class_name: 'Episode', as: 'episodes', label: 'Episodes'
      # The composer of the movie or TV/radio soundtrack.
      property :music_by, class_names: %w[Person MusicGroup], as: 'musicBy', label: 'Music by'
      # The number of episodes in this season or series.
      property :number_of_episodes, class_name: 'Number', as: 'numberOfEpisodes', label: 'Number of Episodes'
      # The number of seasons in this series.
      property :number_of_seasons, class_name: 'Number', as: 'numberOfSeasons', label: 'Number of Seasons'
      # The producer of the movie, tv/radio series, season, or episode, or video.
      property :producer, class_name: 'Person', as: 'producer', label: 'Producer'
      # The production company or studio that made the movie, tv/radio series, season, or episode, or media object.
      property :production_company, class_name: 'Organization', as: 'productionCompany', label: 'Production Company'
      # A season in a tv/radio series.
      property :season, class_name: 'Season', as: 'season', label: 'Season'
      # A season in a tv/radio series. (legacy spelling; see singular form, season)
      property :seasons, class_name: 'Season', as: 'seasons', label: 'Seasons'
      # The start date and time of the event or item (in ISO 8601 date format).
      property :start_date, class_name: 'Date', as: 'startDate', label: 'Start Date'
      # The trailer of a movie or tv/radio series, season, or episode.
      property :trailer, class_name: 'VideoObject', as: 'trailer', label: 'Trailer'
    end
  end
end

