# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/intangible'

module Hotmeal
  module Schema
    # Service
    #
    # @see http://schema.org/Service
    #
    # Subtypes:
    # @see GovernmentService
    class Service < Intangible
      # A means of accessing the service (e.g. a phone bank, a web site, a location, etc.)
      property :available_channel, class_name: 'ServiceChannel', as: 'availableChannel', label: 'Available Channel'
      # The tangible thing generated by the service, e.g. a passport, permit, etc.
      property :produces, class_name: 'Thing', as: 'produces', label: 'Produces'
      # The organization or agency that is providing the service.
      property :provider, class_names: %w[Organization Person], as: 'provider', label: 'Provider'
      # The geographic area where the service is provided.
      property :service_area, class_name: 'AdministrativeArea', as: 'serviceArea', label: 'Service Area'
      # The audience eligible for this service.
      property :service_audience, class_name: 'Audience', as: 'serviceAudience', label: 'Service Audience'
      # The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
      property :service_type, class_name: 'Text', as: 'serviceType', label: 'Service Type'
    end
  end
end

