# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/communicate_action'

module Hotmeal
  module Schema
    # Share Action
    #
    # @see http://schema.org/ShareAction
    class ShareAction < CommunicateAction
    end
  end
end
