# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/store'

module Hotmeal
  module Schema
    # Shoe Store
    #
    # A shoe store.
    # @see http://schema.org/ShoeStore
    class ShoeStore < Store
    end
  end
end

