# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Shopping Center
    #
    # A shopping center or mall.
    # @see http://schema.org/ShoppingCenter
    class ShoppingCenter < LocalBusiness
    end
  end
end

