# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/residence'

module Hotmeal
  module Schema
    # Single Family Residence
    #
    # @see http://schema.org/SingleFamilyResidence
    class SingleFamilyResidence < Residence
    end
  end
end
