# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/residence'

module Hotmeal
  module Schema
    # Single Family Residence
    #
    # Residence type: Single-family home.
    # @see http://schema.org/SingleFamilyResidence
    class SingleFamilyResidence < Residence
    end
  end
end

