# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/web_page_element'

module Hotmeal
  module Schema
    # Site Navigation Element
    #
    # A navigation element of the page.
    # @see http://schema.org/SiteNavigationElement
    class SiteNavigationElement < WebPageElement
    end
  end
end

