# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/sports_activity_location'

module Hotmeal
  module Schema
    # Ski Resort
    #
    # A ski resort.
    # @see http://schema.org/SkiResort
    class SkiResort < SportsActivityLocation
    end
  end
end

