# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Social Event
    #
    # Event type: Social event.
    # @see http://schema.org/SocialEvent
    class SocialEvent < Event
    end
  end
end

