# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Some Products
    #
    # A placeholder for multiple similar products of the same kind.
    # @see http://schema.org/SomeProducts
    class SomeProducts < Product
      # The current approximate inventory level for the item or items.
      property :inventory_level, class_name: 'QuantitativeValue', as: 'inventoryLevel', label: 'Inventory Level'
    end
  end
end

