# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/enumeration'

module Hotmeal
  module Schema
    # Specialty
    #
    # @see http://schema.org/Specialty
    #
    # Subtypes:
    # @see MedicalSpecialty
    class Specialty < Enumeration
    end
  end
end
