# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/enumeration'

module Hotmeal
  module Schema
    # Specialty
    #
    # Any branch of a field in which people typically develop specific expertise, usually after significant study, time, and effort.
    # @see http://schema.org/Specialty
    #
    # Subtypes:
    # @see MedicalSpecialty
    class Specialty < Enumeration
    end
  end
end

