# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Sports Event
    #
    # Event type: Sports event.
    # @see http://schema.org/SportsEvent
    class SportsEvent < Event
    end
  end
end

