# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/store'

module Hotmeal
  module Schema
    # Sporting Goods Store
    #
    # @see http://schema.org/SportingGoodsStore
    class SportingGoodsStore < Store
    end
  end
end

