# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/sports_activity_location'

module Hotmeal
  module Schema
    # Sports Club
    #
    # @see http://schema.org/SportsClub
    class SportsClub < SportsActivityLocation
    end
  end
end

