# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Sports Club
    #
    # A sports club.
    # @see http://schema.org/SportsClub
    class SportsClub < SportsActivityLocation
    end
  end
end

