# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/local_business'

module Hotmeal
  module Schema
    # Sports Activity Location
    #
    # A sports location, such as a playing field.
    # @see http://schema.org/SportsActivityLocation
    #
    # Subtypes:
    # @see BowlingAlley
    # @see ExerciseGym
    # @see GolfCourse
    # @see HealthClub
    # @see PublicSwimmingPool
    # @see SkiResort
    # @see SportsClub
    # @see StadiumOrArena
    # @see TennisComplex
    class SportsActivityLocation < LocalBusiness
    end
  end
end

