# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Stadium or Arena
    #
    # A stadium.
    # @see http://schema.org/StadiumOrArena
    class StadiumOrArena < CivicStructure
    end
  end
end

