# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/administrative_area'

module Hotmeal
  module Schema
    # State
    #
    # @see http://schema.org/State
    class State < AdministrativeArea
    end
  end
end

