# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/local_business'

module Hotmeal
  module Schema
    # Store
    #
    # A retail good store.
    # @see http://schema.org/Store
    #
    # Subtypes:
    # @see AutoPartsStore
    # @see BikeStore
    # @see BookStore
    # @see ClothingStore
    # @see ComputerStore
    # @see ConvenienceStore
    # @see DepartmentStore
    # @see ElectronicsStore
    # @see Florist
    # @see FurnitureStore
    # @see GardenStore
    # @see GroceryStore
    # @see HardwareStore
    # @see HobbyShop
    # @see HomeGoodsStore
    # @see JewelryStore
    # @see LiquorStore
    # @see MensClothingStore
    # @see MobilePhoneStore
    # @see MovieRentalStore
    # @see MusicStore
    # @see OfficeEquipmentStore
    # @see OutletStore
    # @see PawnShop
    # @see PetStore
    # @see ShoeStore
    # @see SportingGoodsStore
    # @see TireShop
    # @see ToyStore
    # @see WholesaleStore
    class Store < LocalBusiness
    end
  end
end

