# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Structured Value
    #
    # Structured values are strings—for example, addresses—that have certain constraints on their structure.
    # @see http://schema.org/StructuredValue
    #
    # Subtypes:
    # @see ContactPoint
    # @see GeoCoordinates
    # @see GeoShape
    # @see NutritionInformation
    # @see OpeningHoursSpecification
    # @see OwnershipInfo
    # @see PriceSpecification
    # @see QuantitativeValue
    # @see TypeAndQuantityNode
    # @see WarrantyPromise
    class StructuredValue < Intangible
    end
  end
end

