# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/interact_action'

module Hotmeal
  module Schema
    # Subscribe Action
    #
    # @see http://schema.org/SubscribeAction
    class SubscribeAction < InteractAction
    end
  end
end
