# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/civic_structure'

module Hotmeal
  module Schema
    # Subway Station
    #
    # @see http://schema.org/SubwayStation
    class SubwayStation < CivicStructure
    end
  end
end

