# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Subway Station
    #
    # A subway station.
    # @see http://schema.org/SubwayStation
    class SubwayStation < CivicStructure
    end
  end
end

