# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_entity'

module Hotmeal
  module Schema
    # Superficial Anatomy
    #
    # @see http://schema.org/SuperficialAnatomy
    class SuperficialAnatomy < MedicalEntity
      # If applicable, a description of the pathophysiology associated with the anatomical system, including potential abnormal changes in the mechanical, physical, and biochemical functions of the system.
      property :associated_pathophysiology, class_name: 'Text', as: 'associatedPathophysiology', label: 'Associated Pathophysiology'
      # Anatomical systems or structures that relate to the superficial anatomy.
      property :related_anatomy, class_names: %w(AnatomicalStructure AnatomicalSystem), as: 'relatedAnatomy', label: 'Related Anatomy'
      # A medical condition associated with this anatomy.
      property :related_condition, class_name: 'MedicalCondition', as: 'relatedCondition', label: 'Related Condition'
      # A medical therapy related to this anatomy.
      property :related_therapy, class_name: 'MedicalTherapy', as: 'relatedTherapy', label: 'Related Therapy'
      # The significance associated with the superficial anatomy; as an example, how characteristics of the superficial anatomy can suggest underlying medical conditions or courses of treatment.
      property :significance, class_name: 'Text', as: 'significance', label: 'Significance'
    end
  end
end
