# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Synagogue
    #
    # A synagogue.
    # @see http://schema.org/Synagogue
    class Synagogue < PlaceOfWorship
    end
  end
end

