# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/place_of_worship'

module Hotmeal
  module Schema
    # Synagogue
    #
    # @see http://schema.org/Synagogue
    class Synagogue < PlaceOfWorship
    end
  end
end
