# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Table
    #
    # A table on the page.
    # @see http://schema.org/Table
    class Table < WebPageElement
    end
  end
end

