# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/web_page_element'

module Hotmeal
  module Schema
    # Table
    #
    # @see http://schema.org/Table
    class Table < WebPageElement
    end
  end
end

