# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/transfer_action'

module Hotmeal
  module Schema
    # Take Action
    #
    # @see http://schema.org/TakeAction
    class TakeAction < TransferAction
    end
  end
end

