# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/civic_structure'

module Hotmeal
  module Schema
    # Taxi Stand
    #
    # @see http://schema.org/TaxiStand
    class TaxiStand < CivicStructure
    end
  end
end
