# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Taxi Stand
    #
    # A taxi stand.
    # @see http://schema.org/TaxiStand
    class TaxiStand < CivicStructure
    end
  end
end

