# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Television Station
    #
    # A television station.
    # @see http://schema.org/TelevisionStation
    class TelevisionStation < LocalBusiness
    end
  end
end

