# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/sports_activity_location'

module Hotmeal
  module Schema
    # Tennis Complex
    #
    # @see http://schema.org/TennisComplex
    class TennisComplex < SportsActivityLocation
    end
  end
end

