# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/performing_group'

module Hotmeal
  module Schema
    # Theater Group
    #
    # @see http://schema.org/TheaterGroup
    class TheaterGroup < PerformingGroup
    end
  end
end

