# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Theater Group
    #
    # A theater group or company—for example, the Royal Shakespeare Company or Druid Theatre.
    # @see http://schema.org/TheaterGroup
    class TheaterGroup < PerformingGroup
    end
  end
end

