# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Therapeutic Procedure
    #
    # A medical procedure intended primarly for therapeutic purposes, aimed at improving a health condition.
    # @see http://schema.org/TherapeuticProcedure
    class TherapeuticProcedure < MedicalProcedure
    end
  end
end

