# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_procedure'

module Hotmeal
  module Schema
    # Therapeutic Procedure
    #
    # @see http://schema.org/TherapeuticProcedure
    class TherapeuticProcedure < MedicalProcedure
    end
  end
end
