# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/achieve_action'

module Hotmeal
  module Schema
    # Tie Action
    #
    # @see http://schema.org/TieAction
    class TieAction < AchieveAction
    end
  end
end
