# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/store'

module Hotmeal
  module Schema
    # Tire Shop
    #
    # @see http://schema.org/TireShop
    class TireShop < Store
    end
  end
end

