# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/place'

module Hotmeal
  module Schema
    # Tourist Attraction
    #
    # @see http://schema.org/TouristAttraction
    class TouristAttraction < Place
    end
  end
end

