# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Tourist Information Center
    #
    # A tourist information center.
    # @see http://schema.org/TouristInformationCenter
    class TouristInformationCenter < LocalBusiness
    end
  end
end

