# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/find_action'

module Hotmeal
  module Schema
    # Track Action
    #
    # @see http://schema.org/TrackAction
    class TrackAction < FindAction
      # A sub property of instrument. The method of delivery
      property :delivery_method, class_name: 'DeliveryMethod', as: 'deliveryMethod', label: 'Delivery Method'
    end
  end
end

