# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/action'

module Hotmeal
  module Schema
    # Trade Action
    #
    # @see http://schema.org/TradeAction
    #
    # Subtypes:
    # @see BuyAction
    # @see DonateAction
    # @see OrderAction
    # @see PayAction
    # @see QuoteAction
    # @see RentAction
    # @see SellAction
    # @see TipAction
    class TradeAction < Action
      # The offer price of a product, or of a price component when attached to PriceSpecification and its subtypes.
      property :price, class_names: %w(Text Number), as: 'price', label: 'Price'
    end
  end
end
