# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/civic_structure'

module Hotmeal
  module Schema
    # Train Station
    #
    # A train station.
    # @see http://schema.org/TrainStation
    class TrainStation < CivicStructure
    end
  end
end

