# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_indication'

module Hotmeal
  module Schema
    # Treatment Indication
    #
    # An indication for treating an underlying condition, symptom, etc.
    # @see http://schema.org/TreatmentIndication
    class TreatmentIndication < MedicalIndication
    end
  end
end

