# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_indication'

module Hotmeal
  module Schema
    # Treatment Indication
    #
    # @see http://schema.org/TreatmentIndication
    class TreatmentIndication < MedicalIndication
    end
  end
end

