# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # TV Series
    #
    # A television series.
    # @see http://schema.org/TVSeries
    class TVSeries < CreativeWork
      # A cast member of the movie, TV series, season, or episode, or video.
      property :actor, class_name: 'Person', as: 'actor', label: 'Actor'
      # A cast member of the movie, TV series, season, or episode, or video. (legacy spelling; see singular form, actor)
      property :actors, class_name: 'Person', as: 'actors', label: 'Actors'
      # The director of the movie, TV episode, or series.
      property :director, class_name: 'Person', as: 'director', label: 'Director'
      # The end date and time of the event (in ISO 8601 date format).
      property :end_date, class_name: 'Date', as: 'endDate', label: 'End Date'
      # An episode of a TV series or season.
      property :episode, class_name: 'TVEpisode', as: 'episode', label: 'Episode'
      # The episode of a TV series or season (legacy spelling; see singular form, episode).
      property :episodes, class_name: 'TVEpisode', as: 'episodes', label: 'Episodes'
      # The composer of the movie or TV soundtrack.
      property :music_by, class_names: %w[Person MusicGroup], as: 'musicBy', label: 'Music by'
      # The number of episodes in this season or series.
      property :number_of_episodes, class_name: 'Number', as: 'numberOfEpisodes', label: 'Number of Episodes'
      # The producer of the movie, TV series, season, or episode, or video.
      property :producer, class_name: 'Person', as: 'producer', label: 'Producer'
      # The production company or studio that made the movie, TV series, season, or episode, or video.
      property :production_company, class_name: 'Organization', as: 'productionCompany', label: 'Production Company'
      # A season of a TV series.
      property :season, class_name: 'TVSeason', as: 'season', label: 'Season'
      # The seasons of the TV series (legacy spelling; see singular form, season).
      property :seasons, class_name: 'TVSeason', as: 'seasons', label: 'Seasons'
      # The start date and time of the event (in ISO 8601 date format).
      property :start_date, class_name: 'Date', as: 'startDate', label: 'Start Date'
      # The trailer of the movie or TV series, season, or episode.
      property :trailer, class_name: 'VideoObject', as: 'trailer', label: 'Trailer'
    end
  end
end

