# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/creative_work'

module Hotmeal
  module Schema
    # TV Series
    #
    # @see http://schema.org/TVSeries
    class TVSeries < CreativeWork
    end
  end
end

