# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/creative_work'

module Hotmeal
  module Schema
    # TV Season
    #
    # @see http://schema.org/TVSeason
    class TVSeason < CreativeWork
      # The end date and time of the event (in ISO 8601 date format).
      property :end_date, class_name: 'Date', as: 'endDate', label: 'End Date'
      # An episode of a TV series or season.
      property :episode, class_name: 'TVEpisode', as: 'episode', label: 'Episode'
      # The episode of a TV series or season (legacy spelling; see singular form, episode).
      property :episodes, class_name: 'TVEpisode', as: 'episodes', label: 'Episodes'
      # The number of episodes in this season or series.
      property :number_of_episodes, class_name: 'Number', as: 'numberOfEpisodes', label: 'Number of Episodes'
      # The TV series to which this episode or season belongs.
      property :part_of_tv_series, class_name: 'TVSeries', as: 'partOfTVSeries', label: 'Part of TV Series'
      # The season number.
      property :season_number, class_name: 'Integer', as: 'seasonNumber', label: 'Season Number'
      # The start date and time of the event (in ISO 8601 date format).
      property :start_date, class_name: 'Date', as: 'startDate', label: 'Start Date'
      # The trailer of the movie or TV series, season, or episode.
      property :trailer, class_name: 'VideoObject', as: 'trailer', label: 'Trailer'
    end
  end
end

