# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Type And Quantity Node
    #
    # A structured value indicating the quantity, unit of measurement, and business function of goods included in a bundle offer.
    # @see http://schema.org/TypeAndQuantityNode
    class TypeAndQuantityNode < StructuredValue
      # The quantity of the goods included in the offer.
      property :amount_of_this_good, class_name: 'Number', as: 'amountOfThisGood', label: 'Amount of This Good'
      # The business function (e.g. sell, lease, repair, dispose) of the offer or component of a bundle (TypeAndQuantityNode). The default is http://purl.org/goodrelations/v1#Sell.
      property :business_function, class_name: 'BusinessFunction', as: 'businessFunction', label: 'Business Function'
      # The product that this structured value is referring to.
      property :type_of_good, class_name: 'Product', as: 'typeOfGood', label: 'Type of Good'
      # The unit of measurement given using the UN/CEFACT Common Code (3 characters).
      property :unit_code, class_name: 'Text', as: 'unitCode', label: 'Unit Code'
    end
  end
end

