# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/price_specification'

module Hotmeal
  module Schema
    # Unit Price Specification
    #
    # @see http://schema.org/UnitPriceSpecification
    class UnitPriceSpecification < PriceSpecification
      # This property specifies the minimal quantity and rounding increment that will be the basis for the billing. The unit of measurement is specified by the unitCode property.
      property :billing_increment, class_name: 'Number', as: 'billingIncrement', label: 'Billing Increment'
      # A short text or acronym indicating multiple price specifications for the same offer, e.g. SRP for the suggested retail price or INVOICE for the invoice price, mostly used in the car industry.
      property :price_type, class_name: 'Text', as: 'priceType', label: 'Price Type'
      # The unit of measurement given using the UN/CEFACT Common Code (3 characters).
      property :unit_code, class_name: 'Text', as: 'unitCode', label: 'Unit Code'
    end
  end
end

