# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # User Checkins
    #
    # User interaction: Check-in at a place.
    # @see http://schema.org/UserCheckins
    class UserCheckins < UserInteraction
    end
  end
end

