# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/user_interaction'

module Hotmeal
  module Schema
    # User Page Visits
    #
    # @see http://schema.org/UserPageVisits
    class UserPageVisits < UserInteraction
    end
  end
end

