# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/user_interaction'

module Hotmeal
  module Schema
    # User Blocks
    #
    # User interaction: Block this content.
    # @see http://schema.org/UserBlocks
    class UserBlocks < UserInteraction
    end
  end
end

