# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # User Comments
    #
    # The UserInteraction event in which a user comments on an item.
    # @see http://schema.org/UserComments
    class UserComments < UserInteraction
      # The text of the UserComment.
      property :comment_text, class_name: 'Text', as: 'commentText', label: 'Comment Text'
      # The time at which the UserComment was made.
      property :comment_time, class_name: 'Date', as: 'commentTime', label: 'Comment Time'
      # The creator/author of this CreativeWork or UserComments. This is the same as the Author property for CreativeWork.
      property :creator, class_names: %w[Organization Person], as: 'creator', label: 'Creator'
      # Specifies the CreativeWork associated with the UserComment.
      property :discusses, class_name: 'CreativeWork', as: 'discusses', label: 'Discusses'
      # The URL at which a reply may be posted to the specified UserComment.
      property :reply_to_url, class_name: 'URL', as: 'replyToUrl', label: 'Reply to Url'
    end
  end
end

