# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # User Interaction
    #
    # A user interacting with a page
    # @see http://schema.org/UserInteraction
    #
    # Subtypes:
    # @see UserBlocks
    # @see UserCheckins
    # @see UserComments
    # @see UserDownloads
    # @see UserLikes
    # @see UserPageVisits
    # @see UserPlays
    # @see UserPlusOnes
    # @see UserTweets
    class UserInteraction < Event
    end
  end
end

