# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # User Plays
    #
    # User interaction: Play count of an item, for example a video or a song.
    # @see http://schema.org/UserPlays
    class UserPlays < UserInteraction
    end
  end
end

