# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/user_interaction'

module Hotmeal
  module Schema
    # User Tweets
    #
    # User interaction: Tweets.
    # @see http://schema.org/UserTweets
    class UserTweets < UserInteraction
    end
  end
end

