# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/user_interaction'

module Hotmeal
  module Schema
    # User Checkins
    #
    # @see http://schema.org/UserCheckins
    class UserCheckins < UserInteraction
    end
  end
end

