# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/anatomical_structure'

module Hotmeal
  module Schema
    # Vessel
    #
    # @see http://schema.org/Vessel
    #
    # Subtypes:
    # @see Artery
    # @see LymphaticVessel
    # @see Vein
    class Vessel < AnatomicalStructure
    end
  end
end

