# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/medical_organization'

module Hotmeal
  module Schema
    # Veterinary Care
    #
    # @see http://schema.org/VeterinaryCare
    class VeterinaryCare < MedicalOrganization
    end
  end
end
