# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/medical_organization'

module Hotmeal
  module Schema
    # Veterinary Care
    #
    # A vet's office.
    # @see http://schema.org/VeterinaryCare
    class VeterinaryCare < MedicalOrganization
    end
  end
end

