# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Video Gallery
    #
    # Web page type: Video gallery page.
    # @see http://schema.org/VideoGallery
    class VideoGallery < CollectionPage
    end
  end
end

