# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/event'

module Hotmeal
  module Schema
    # Visual Arts Event
    #
    # Event type: Visual arts event.
    # @see http://schema.org/VisualArtsEvent
    class VisualArtsEvent < Event
    end
  end
end

