# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/landform'

module Hotmeal
  module Schema
    # Volcano
    #
    # @see http://schema.org/Volcano
    class Volcano < Landform
    end
  end
end

