# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Volcano
    #
    # A volcano, like Fuji san
    # @see http://schema.org/Volcano
    class Volcano < Landform
    end
  end
end

