# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/react_action'

module Hotmeal
  module Schema
    # Want Action
    #
    # @see http://schema.org/WantAction
    class WantAction < ReactAction
    end
  end
end

