# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/structured_value'

module Hotmeal
  module Schema
    # Warranty Promise
    #
    # A structured value representing the duration and scope of services that will be provided to a customer free of charge in case of a defect or malfunction of a product.
    # @see http://schema.org/WarrantyPromise
    class WarrantyPromise < StructuredValue
      # The duration of the warranty promise. Common unitCode values are ANN for year, MON for months, or DAY for days.
      property :duration_of_warranty, class_name: 'QuantitativeValue', as: 'durationOfWarranty', label: 'Duration of Warranty'
      # The scope of the warranty promise.
      property :warranty_scope, class_name: 'WarrantyScope', as: 'warrantyScope', label: 'Warranty Scope'
    end
  end
end

