# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/enumeration'

module Hotmeal
  module Schema
    # Warranty Scope
    #
    # @see http://schema.org/WarrantyScope
    class WarrantyScope < Enumeration
    end
  end
end
