# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/body_of_water'

module Hotmeal
  module Schema
    # Waterfall
    #
    # @see http://schema.org/Waterfall
    class Waterfall < BodyOfWater
    end
  end
end

