# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/body_of_water'

module Hotmeal
  module Schema
    # Waterfall
    #
    # A waterfall, like Niagara
    # @see http://schema.org/Waterfall
    class Waterfall < BodyOfWater
    end
  end
end

