# This file is automatically generated using http://schema.rdfs.org/all.json
# 2014-04-03
require 'hotmeal/schema'
require 'hotmeal/schema/use_action'

module Hotmeal
  module Schema
    # Wear Action
    #
    # @see http://schema.org/WearAction
    class WearAction < UseAction
    end
  end
end
