# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/use_action'

module Hotmeal
  module Schema
    # Wear Action
    #
    # @see http://schema.org/WearAction
    class WearAction < UseAction
    end
  end
end

