# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Web Page Element
    #
    # A web page element, like a table or an image
    # @see http://schema.org/WebPageElement
    #
    # Subtypes:
    # @see SiteNavigationElement
    # @see Table
    # @see WPAdBlock
    # @see WPFooter
    # @see WPHeader
    # @see WPSideBar
    class WebPageElement < CreativeWork
    end
  end
end

