# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/software_application'

module Hotmeal
  module Schema
    # Web Application
    #
    # Web applications.
    # @see http://schema.org/WebApplication
    class WebApplication < SoftwareApplication
      # Specifies browser requirements in human-readable text. For example,"requires HTML5 support".
      property :browser_requirements, class_name: 'Text', as: 'browserRequirements', label: 'Browser Requirements'
    end
  end
end

