# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-08-28
require 'hotmeal/schema'
require 'hotmeal/schema/creative_work'

module Hotmeal
  module Schema
    # Web Page Element
    #
    # @see http://schema.org/WebPageElement
    #
    # Subtypes:
    # @see SiteNavigationElement
    # @see Table
    # @see WPAdBlock
    # @see WPFooter
    # @see WPHeader
    # @see WPSideBar
    class WebPageElement < CreativeWork
    end
  end
end

