# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/store'

module Hotmeal
  module Schema
    # Wholesale Store
    #
    # A wholesale store.
    # @see http://schema.org/WholesaleStore
    class WholesaleStore < Store
    end
  end
end

