# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/web_page_element'

module Hotmeal
  module Schema
    # WP Ad Block
    #
    # An advertising section of the page.
    # @see http://schema.org/WPAdBlock
    class WPAdBlock < WebPageElement
    end
  end
end

