# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # WP Footer
    #
    # The footer section of the page.
    # @see http://schema.org/WPFooter
    class WPFooter < WebPageElement
    end
  end
end

