# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # WP Header
    #
    # The header section of the page.
    # @see http://schema.org/WPHeader
    class WPHeader < WebPageElement
    end
  end
end

