# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'hotmeal/schema/web_page_element'

module Hotmeal
  module Schema
    # WP Side Bar
    #
    # A sidebar section of the page.
    # @see http://schema.org/WPSideBar
    class WPSideBar < WebPageElement
    end
  end
end

