# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Boolean
    #
    # Boolean: True or False.
    # @see http://schema.org/Boolean
    class Boolean < DataType
    end
  end
end

