# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'
require 'delegate'

module Hotmeal
  module Schema
    # Data Type
    #
    # The basic data types such as Integers, Strings, etc.
    # @see http://schema.org/DataType
    #
    # Subtypes:
    # @see Boolean
    # @see Date
    # @see DateTime
    # @see Number
    # @see Text
    # @see Time
    class DataType < SimpleDelegator
    end
  end
end

