# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Date
    #
    # A date value in ISO 8601 date format.
    # @see http://schema.org/Date
    class Date < DataType
    end
  end
end

