# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Float
    #
    # Data type: Floating number.
    # @see http://schema.org/Float
    class Float < Number
    end
  end
end

