# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Integer
    #
    # Data type: Integer.
    # @see http://schema.org/Integer
    class Integer < Number
    end
  end
end

