# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # Number
    #
    # Data type: Number.
    # @see http://schema.org/Number
    #
    # Subtypes:
    # @see Float
    # @see Integer
    class Number < DataType
    end
  end
end

