# This file is automatically generated using http://schema.rdfs.org/all.json
# 2013-05-28
require 'hotmeal/schema'

module Hotmeal
  module Schema
    # URL
    #
    # Data type: URL.
    # @see http://schema.org/URL
    class URL < Text
    end
  end
end

